#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
nci_plotter.py

Standalone GUI utility for generating and visualizing NCI plots.

Required input:
    - .wfn
    - .wfx

Rejected input:
    - .out / .log, because ORCA output files do not contain the full
      wavefunction/electron-density information required for NCI/RDG analysis.

Required external program:
    - Multiwfn

How to run:
    python nci_plotter.py

Main controls:
    - Select wavefunction file.
    - Select Multiwfn executable.
    - Generate NCI data through Multiwfn batch mode.
    - Display RDG isosurface colored by sign(lambda2)rho in PyVista.
    - Adjust RDG isovalue, opacity, color range, colormap, molecule visibility,
      bond visibility, scalar bar visibility, and background color.

Important scientific constraint:
    This script does NOT generate fake or approximate NCI plots.
    It only visualizes actual volumetric data generated by Multiwfn from the
    selected wavefunction file.
"""

from __future__ import annotations

import json
import os
import queue
import re
import shutil
import subprocess
import sys
import threading
import time
import webbrowser
from dataclasses import dataclass
from pathlib import Path
from typing import Optional, Tuple

import numpy as np

try:
    import tkinter as tk
    from tkinter import filedialog, messagebox, ttk
except Exception as exc:
    raise RuntimeError("Tkinter is required but could not be imported.") from exc


CONFIG_FILE = Path.home() / ".nci_plotter_config.json"
TOOLS_ROOT = Path(__file__).resolve().parents[1]
APP_ROOT = TOOLS_ROOT.parent
if str(TOOLS_ROOT) not in sys.path:
    sys.path.insert(0, str(TOOLS_ROOT))
from app_identity import configure_tk_window_identity, install_dev_reload_shortcut, set_windows_app_id
from shared.tk_helpers import bind_mousewheel_to_canvas, configure_builder_ui_style, executable_filetypes, keep_entry_end_visible, load_header_icon
from shared.pyvista_window import bring_pyvista_window_to_front, save_pyvista_screenshot
from shared.molecule_style import add_mesh_safe, molecule_material_parameters
from shared.multiwfn_locator import find_multiwfn, find_multiwfn_deep
from shared.window_layout import compute_visualization_layout, place_visualization_windows

NCI_ICON_PATH = TOOLS_ROOT / "images" / "tr_NCI_icon.png"
COPYRIGHT_NOTE = "(c) Yury Torubaev, 2026"
GITHUB_URL = "https://github.com/torubaev/crystengkit-orca-v1.0"
AI_ASSISTANT_URL = "https://chatgpt.com/g/g-6a6063dcc6b88191b88ac7a6c3b9476d-crystengkit-orca-assistant"
CONTACT_EMAIL = "torubaev(at)gmail.com"
LINKEDIN_URL = "https://www.linkedin.com/in/torubaev/"
README_LINK_TEXT = "README section: NCI Plotter"
README_ANCHOR = "nci-plotter"
CITATION_REFERENCE = (
    "Torubaev, Y. CrystEngKit-ORCA: practical GUI tools for ORCA and "
    "Multiwfn calculations in supramolecular chemistry and crystal engineering, "
    "version 1.0; GitHub, 2026. https://github.com/torubaev/crystengkit-orca-v1.0"
)
CITATION_TEXT = f"Cite as: {CITATION_REFERENCE}"


def wiki_url() -> str:
    return GITHUB_URL + f"#{README_ANCHOR}"


def open_readme_or_wiki() -> None:
    webbrowser.open(wiki_url(), new=2)
ABOUT_PURPOSE = (
    "Creates noncovalent-interaction surfaces from .wfn or .wfx files. It is useful for "
    "visualizing weak contacts, attractive regions, and repulsive regions in molecular "
    "associates, and it can open the NCI + QTAIM overlay viewer when matching topology "
    "files are available."
)
MAX_RECENT_FILES = 5
IMAGE_PRESETS = {
    "Viewer window": None,
    "Preview: 1600 x 1200 px": (1600, 1200),
    "Paper 300 dpi: 3000 x 2250 px": (3000, 2250),
    "Paper 600 dpi: 6000 x 4500 px": (6000, 4500),
    "Poster / high-res: 8000 x 6000 px": (8000, 6000),
}
DEFAULT_IMAGE_PRESET = "Paper 300 dpi: 3000 x 2250 px"

SUPPORTED_WAVEFUNCTION_EXTS = {".wfn", ".wfx"}
REJECTED_EXTS = {".out", ".log"}
ELEMENT_SYMBOLS = {
    "H", "He", "Li", "Be", "B", "C", "N", "O", "F", "Ne", "Na", "Mg", "Al", "Si", "P", "S", "Cl", "Ar",
    "K", "Ca", "Sc", "Ti", "V", "Cr", "Mn", "Fe", "Co", "Ni", "Cu", "Zn", "Ga", "Ge", "As", "Se", "Br", "Kr",
    "Rb", "Sr", "Y", "Zr", "Nb", "Mo", "Tc", "Ru", "Rh", "Pd", "Ag", "Cd", "In", "Sn", "Sb", "Te", "I", "Xe",
    "Cs", "Ba", "La", "Ce", "Pr", "Nd", "Pm", "Sm", "Eu", "Gd", "Tb", "Dy", "Ho", "Er", "Tm", "Yb", "Lu",
    "Hf", "Ta", "W", "Re", "Os", "Ir", "Pt", "Au", "Hg", "Tl", "Pb", "Bi", "Po", "At", "Rn", "Fr", "Ra", "Ac",
    "Th", "Pa", "U", "Np", "Pu", "Am", "Cm", "Bk", "Cf", "Es", "Fm", "Md", "No", "Lr", "Rf", "Db", "Sg", "Bh",
    "Hs", "Mt", "Ds", "Rg", "Cn", "Nh", "Fl", "Mc", "Lv", "Ts", "Og",
}


def element_symbol_from_wfn_label(label: str) -> Optional[str]:
    match = re.match(r"^([A-Za-z]{1,3})\d*$", label.strip())
    if not match:
        return None
    letters = match.group(1)
    candidates = [letters[:1].upper() + letters[1:].lower()]
    if len(letters) >= 2:
        candidates.append(letters[:1].upper() + letters[1:2].lower())
    for candidate in candidates:
        if candidate in ELEMENT_SYMBOLS:
            return candidate
    return None


def configure_pyvista_defaults(pv_module, plotter, background="black", parallel_projection=True, antialiasing=None, extent=1.0):
    """Apply conservative PyVista defaults that work on limited OpenGL contexts."""
    try:
        pv_module.global_theme.multi_samples = 0
    except Exception:
        pass

    try:
        pv_module.global_theme.smooth_shading = False
    except Exception:
        pass

    try:
        bg = str(background or "black").strip().lower()
        plotter.set_background(background, top=HQ_BACKGROUND_TOP.get(bg))
    except Exception:
        try:
            plotter.set_background("black")
        except Exception:
            pass

    if antialiasing:
        try:
            plotter.enable_anti_aliasing(antialiasing)
        except Exception:
            pass

    try:
        plotter.enable_depth_peeling(number_of_peels=8, occlusion_ratio=0.0)
    except Exception:
        pass

    try:
        plotter.renderer.SetTwoSidedLighting(True)
    except Exception:
        pass

    if parallel_projection:
        try:
            plotter.enable_parallel_projection()
        except Exception:
            pass

    try:
        plotter.remove_all_lights()
    except Exception:
        pass

    try:
        extent = max(float(extent), 1.0)
    except Exception:
        extent = 1.0

    light_specs = [
        ("headlight", None, 0.72),
        ("camera light", None, 0.34),
        ("scene light", (2.6 * extent, -3.4 * extent, 4.2 * extent), 0.56),
        ("scene light", (-3.0 * extent, 2.4 * extent, 3.6 * extent), 0.30),
        ("scene light", (0.0, 3.2 * extent, -2.6 * extent), 0.18),
    ]

    for light_type, position, intensity in light_specs:
        try:
            if light_type in {"headlight", "camera light"}:
                light = pv_module.Light(light_type=light_type)
            else:
                light = pv_module.Light(
                    position=position,
                    focal_point=(0.0, 0.0, 0.0),
                    color="white",
                    light_type="scene light",
                )
            light.intensity = intensity
            plotter.add_light(light)
        except Exception:
            pass


LEGACY_SAFE_MULTIWFN_TEMPLATE = """\
# Multiwfn batch-command template.
#
# IMPORTANT:
# Multiwfn menu numbers can differ between versions.
# Replace this template with the exact command sequence that generates:
#   1) RDG cube
#   2) sign(lambda2)rho cube
#
# The command is run internally as:
#   Multiwfn input.wfn < multiwfn_nci_input.txt
#
# The default template only exits Multiwfn. It is intentionally safe.
# It will NOT generate NCI data until you replace it with a validated
# command sequence for your installed Multiwfn version.
q
"""

DEFAULT_MULTIWFN_TEMPLATE = """\
# Multiwfn 2026.x NCI/RDG cube export template.
#
# Expected Multiwfn route:
#   20  = Visual study of weak interaction
#   1   = NCI analysis
#   3   = High-quality grid covering the whole system
#   3   = Output cube files to func1.cub and func2.cub
#   0   = Return / exit from post-processing menu
#   q   = Quit Multiwfn
#
# Multiwfn convention for this NCI export:
#   func1.cub = sign(lambda2)rho
#   func2.cub = RDG
#
# If this sequence does not match your exact Multiwfn build, edit it from:
#   Edit Multiwfn command template
20
1
3
3
0
q
"""


COVALENT_RADII = {
    1: 0.31,
    2: 0.28,
    3: 1.28,
    4: 0.96,
    5: 0.84,
    6: 0.76,
    7: 0.71,
    8: 0.66,
    9: 0.57,
    10: 0.58,
    11: 1.66,
    12: 1.41,
    13: 1.21,
    14: 1.11,
    15: 1.07,
    16: 1.05,
    17: 1.02,
    18: 1.06,
    19: 2.03,
    20: 1.76,
    21: 1.70,
    22: 1.60,
    23: 1.53,
    24: 1.39,
    25: 1.39,
    26: 1.32,
    27: 1.26,
    28: 1.24,
    29: 1.32,
    30: 1.22,
    31: 1.22,
    32: 1.20,
    33: 1.19,
    34: 1.20,
    35: 1.20,
    36: 1.16,
    37: 2.20,
    38: 1.95,
    39: 1.90,
    40: 1.75,
    41: 1.64,
    42: 1.54,
    43: 1.47,
    44: 1.46,
    45: 1.42,
    46: 1.39,
    47: 1.45,
    48: 1.44,
    49: 1.42,
    50: 1.39,
    51: 1.39,
    52: 1.38,
    53: 1.39,
    54: 1.40,
    55: 2.44,
    56: 2.15,
    57: 2.07,
    58: 2.04,
    59: 2.03,
    60: 2.01,
    61: 1.99,
    62: 1.98,
    63: 1.98,
    64: 1.96,
    65: 1.94,
    66: 1.92,
    67: 1.92,
    68: 1.89,
    69: 1.90,
    70: 1.87,
    71: 1.87,
    72: 1.75,
    73: 1.70,
    74: 1.62,
    75: 1.51,
    76: 1.44,
    77: 1.41,
    78: 1.36,
    79: 1.36,
    80: 1.32,
    81: 1.45,
    82: 1.46,
    83: 1.48,
    84: 1.40,
    85: 1.50,
    86: 1.50,
    87: 2.60,
    88: 2.21,
    89: 2.15,
    90: 2.06,
    91: 2.00,
    92: 1.96,
    93: 1.90,
    94: 1.87,
    95: 1.80,
    96: 1.69,
}

COVALENT_RADIUS_VARIANTS = {
    "C_sp3": 0.76,
    "C_sp2": 0.73,
    "C_sp": 0.69,
    "Mn_low_spin": 1.39,
    "Mn_high_spin": 1.61,
    "Fe_low_spin": 1.32,
    "Fe_high_spin": 1.52,
    "Co_low_spin": 1.26,
    "Co_high_spin": 1.50,
}


ATOM_COLORS = {
    1: "#E8E8E8",
    3: "#BA75EA",
    5: "#EAA6A6",
    6: "#5F5F5F",
    7: "#2B48D8",
    8: "#CC0000",
    9: "#82CC49",
    11: "#9D55DE",
    12: "#7ED900",
    13: "#AF9999",
    14: "#DDB88F",
    15: "#E67300",
    16: "#E6E62B",
    17: "#1CD91C",
    19: "#833BC2",
    20: "#38E800",
    22: "#AFB2B7",
    23: "#99999E",
    24: "#7F8CB7",
    25: "#8F70B7",
    26: "#CC5D2F",
    27: "#DC8493",
    28: "#49BF49",
    29: "#B8752F",
    30: "#7376A2",
    31: "#B28484",
    32: "#5E8383",
    33: "#AD76D0",
    34: "#EA9400",
    35: "#982626",
    44: "#218282",
    45: "#097382",
    46: "#005F78",
    47: "#B0B0B0",
    48: "#EAC781",
    50: "#5E7575",
    52: "#C27000",
    53: "#850085",
    77: "#154D7B",
    78: "#BFC0CE",
    79: "#EABB20",
    80: "#A9A9BF",
    82: "#575961",
}

NCI_SCALAR_NAME = "sign(lambda2)rho"
NCI_SCALAR_BAR_TITLE = "sign(lambda2)rho\n\n\n"
HQ_ATOM_RESOLUTION = 96
HQ_BOND_RESOLUTION = 72
HQ_BACKGROUND_TOP = {
    "white": "#eef3f8",
    "black": "#171b22",
}


def contrast_text_color(background: str) -> str:
    colors = {
        "white": "black",
        "lightgray": "black",
        "gray": "white",
        "black": "white",
    }
    bg = str(background or "").strip().lower()
    if bg in colors:
        return colors[bg]
    if bg.startswith("#") and len(bg) in {4, 7}:
        try:
            if len(bg) == 4:
                r = int(bg[1] * 2, 16)
                g = int(bg[2] * 2, 16)
                b = int(bg[3] * 2, 16)
            else:
                r = int(bg[1:3], 16)
                g = int(bg[3:5], 16)
                b = int(bg[5:7], 16)
            luminance = (0.2126 * r + 0.7152 * g + 0.0722 * b) / 255.0
            return "black" if luminance > 0.55 else "white"
        except Exception:
            pass
    return "black"


def set_scalar_bar_text_color(plotter, text_color: str, title: str | None = None) -> None:
    try:
        scalar_bars = getattr(plotter, "scalar_bars", {})
        scalar_bar = scalar_bars.get(title) if title else None
        if scalar_bar is None:
            bars = list(scalar_bars.values())
            if not bars:
                return
            scalar_bar = bars[0]
        import pyvista as pv
        rgb = pv.Color(text_color).float_rgb
        title_prop = scalar_bar.GetTitleTextProperty()
        label_prop = scalar_bar.GetLabelTextProperty()
        title_prop.SetColor(*rgb)
        label_prop.SetColor(*rgb)
        title_prop.BoldOn()
        label_prop.BoldOn()
        title_prop.SetFontSize(16)
        label_prop.SetFontSize(12)
    except Exception:
        pass


@dataclass
class CubeData:
    path: Path
    origin: np.ndarray
    axes: np.ndarray
    shape: tuple[int, int, int]
    atom_numbers: list[int]
    atom_coords: np.ndarray
    values: np.ndarray


class CubeParseError(Exception):
    """Raised when a cube file cannot be parsed safely."""


class CubeParser:
    BOHR_TO_ANG = 0.529177210903

    @staticmethod
    def parse(path: Path) -> CubeData:
        if not path.exists():
            raise CubeParseError(f"Cube file not found: {path}")

        try:
            lines = path.read_text(encoding="utf-8", errors="replace").splitlines()
        except Exception as exc:
            raise CubeParseError(f"Could not read cube file: {path}") from exc

        if len(lines) < 6:
            raise CubeParseError(f"Malformed cube file: too few lines: {path}")

        try:
            atom_line = lines[2].split()
            natoms_raw = int(float(atom_line[0]))
            natoms = abs(natoms_raw)

            origin = np.array(
                [float(atom_line[1]), float(atom_line[2]), float(atom_line[3])],
                dtype=float,
            )

            axes = []
            shape = []

            for i in range(3):
                parts = lines[3 + i].split()
                n = int(float(parts[0]))
                shape.append(abs(n))
                axes.append([float(parts[1]), float(parts[2]), float(parts[3])])

            axes_arr = np.array(axes, dtype=float)
            shape_tuple = (shape[0], shape[1], shape[2])

            atom_numbers: list[int] = []
            atom_coords_list = []

            for i in range(natoms):
                parts = lines[6 + i].split()
                atom_numbers.append(int(float(parts[0])))
                atom_coords_list.append(
                    [float(parts[2]), float(parts[3]), float(parts[4])]
                )

            atom_coords = np.array(atom_coords_list, dtype=float)

            data_start = 6 + natoms
            raw_values = []

            for line in lines[data_start:]:
                for token in line.split():
                    raw_values.append(float(token.replace("D", "E").replace("d", "e")))

            expected = shape_tuple[0] * shape_tuple[1] * shape_tuple[2]

            if len(raw_values) < expected:
                raise CubeParseError(
                    f"Malformed cube file: expected {expected} grid values, "
                    f"found {len(raw_values)}: {path}"
                )

            values = np.array(raw_values[:expected], dtype=float).reshape(
                shape_tuple, order="C"
            )

            if natoms_raw > 0:
                origin = origin * CubeParser.BOHR_TO_ANG
                axes_arr = axes_arr * CubeParser.BOHR_TO_ANG
                atom_coords = atom_coords * CubeParser.BOHR_TO_ANG

            return CubeData(
                path=path,
                origin=origin,
                axes=axes_arr,
                shape=shape_tuple,
                atom_numbers=atom_numbers,
                atom_coords=atom_coords,
                values=values,
            )

        except CubeParseError:
            raise
        except Exception as exc:
            raise CubeParseError(f"Malformed cube file: {path}") from exc


def screen_fraction_height(widget: tk.Misc, fraction: float = 0.80, fallback: int = 760) -> int:
    try:
        return max(1, int(widget.winfo_screenheight() * fraction))
    except Exception:
        return fallback


def open_about_dialog(parent: tk.Misc, title: str, icon_path: Path, purpose: str) -> None:
    win = tk.Toplevel(parent)
    win.title("About")
    win.transient(parent)
    win.columnconfigure(0, weight=1)

    def copy_citation(_event=None) -> None:
        try:
            win.clipboard_clear()
            win.clipboard_append(CITATION_REFERENCE)
            citation_label.configure(text="Cite as: copied to clipboard", foreground="#047857")
            win.after(1400, lambda: citation_label.configure(text=CITATION_TEXT, foreground="#1d4ed8") if citation_label.winfo_exists() else None)
        except Exception as exc:
            messagebox.showerror("Copy citation", str(exc), parent=win)

    box = ttk.Frame(win, padding=14)
    box.grid(row=0, column=0, sticky="nsew")
    box.columnconfigure(1, weight=1)

    icon = load_header_icon(icon_path, max_size=144)
    if icon is not None:
        win.about_icon = icon
        ttk.Label(box, image=icon).grid(row=0, column=0, rowspan=8, sticky="n", padx=(0, 18))

    ttk.Label(box, text=title, font=("Segoe UI", 12, "bold")).grid(row=0, column=1, sticky="w")
    ttk.Label(box, text=purpose, justify="left", wraplength=420).grid(row=1, column=1, sticky="w", pady=(8, 0))
    ttk.Separator(box, orient="horizontal").grid(row=2, column=1, sticky="ew", pady=(12, 8))
    ttk.Label(box, text="GitHub", font=("Segoe UI", 9, "bold")).grid(row=3, column=1, sticky="w")
    github_link = ttk.Label(box, text=GITHUB_URL, foreground="#1d4ed8", cursor="hand2", justify="left")
    github_link.grid(row=4, column=1, sticky="w", pady=(2, 0))
    github_link.bind("<Button-1>", lambda _event: webbrowser.open(GITHUB_URL))
    ttk.Label(box, text="Documentation", font=("Segoe UI", 9, "bold")).grid(row=5, column=1, sticky="w", pady=(8, 0))
    wiki_link = ttk.Label(box, text=README_LINK_TEXT, foreground="#1d4ed8", cursor="hand2", justify="left")
    wiki_link.grid(row=6, column=1, sticky="w", pady=(2, 0))
    wiki_link.bind("<Button-1>", lambda _event: open_readme_or_wiki())
    ai_link = ttk.Label(box, text="AI assistant", foreground="#1d4ed8", cursor="hand2", justify="left")
    ai_link.grid(row=7, column=1, sticky="w", pady=(2, 0))
    ai_link.bind("<Button-1>", lambda _event: webbrowser.open(AI_ASSISTANT_URL, new=2))
    citation_label = ttk.Label(box, text=CITATION_TEXT, foreground="#1d4ed8", cursor="hand2", justify="left", wraplength=430)
    citation_label.grid(row=8, column=1, sticky="w", pady=(10, 0))
    citation_label.bind("<Button-1>", copy_citation)
    ttk.Separator(box, orient="horizontal").grid(row=9, column=1, sticky="ew", pady=(12, 8))
    ttk.Label(box, text=COPYRIGHT_NOTE, foreground="#4b5563").grid(row=10, column=1, sticky="w")
    contact = ttk.Frame(box)
    contact.grid(row=11, column=1, sticky="w", pady=(7, 0))
    ttk.Label(contact, text=f"Email: {CONTACT_EMAIL}").grid(row=0, column=0, sticky="w")
    linkedin_icon = tk.Label(contact, text="in", bg="#0a66c2", fg="white", cursor="hand2", font=("Arial", 9, "bold"), padx=4, pady=1)
    linkedin_icon.grid(row=0, column=1, padx=(10, 0))
    linkedin_icon.bind("<Button-1>", lambda _event: webbrowser.open(LINKEDIN_URL))

    ttk.Button(box, text="Close", command=win.destroy).grid(row=12, column=0, columnspan=2, sticky="e", pady=(14, 0))
    win.geometry("620x430")
    win.minsize(560, 390)
    win.grab_set()


class NCIPlotterApp:
    def __init__(self, root, initial_wavefunction_path: Optional[str] = None, *, embedded: bool = False):
        self.root = root
        self.embedded = bool(embedded)
        self.window_height = screen_fraction_height(self.root)
        if not self.embedded:
            self.root.title("NCI Plotter")
            self.root.geometry(f"980x{self.window_height}")
            configure_builder_ui_style(self.root)

        self.config = self.load_config()

        self.wavefunction_path = tk.StringVar(value="")
        self.multiwfn_path = tk.StringVar(value=self.config.get("multiwfn_path", ""))
        self.output_dir = tk.StringVar(value="")

        self.rdg_isovalue = tk.DoubleVar(value=0.50)
        self.opacity = tk.DoubleVar(value=0.75)
        self.color_min = tk.StringVar(value="-0.05")
        self.color_max = tk.StringVar(value="0.05")
        self.colormap = tk.StringVar(value="rainbow")
        self.show_molecule = tk.BooleanVar(value=True)
        self.show_bonds = tk.BooleanVar(value=True)
        self.show_scalar_bar = tk.BooleanVar(value=True)
        self.background = tk.StringVar(value="black")
        self.image_resolution = tk.StringVar(value=self.config.get("image_resolution", DEFAULT_IMAGE_PRESET))

        self.command_template = tk.StringVar(
            value=self.config.get("multiwfn_template", DEFAULT_MULTIWFN_TEMPLATE)
        )

        self.log_queue: queue.Queue[str] = queue.Queue()
        self.progress_status = tk.StringVar(value="Status: Idle")
        self.progress_value = tk.DoubleVar(value=0.0)
        self.progress_percent_value = 0.0

        self.rdg_cube: Optional[CubeData] = None
        self.signrho_cube: Optional[CubeData] = None
        self.rdg_cube_path: Optional[Path] = None
        self.signrho_cube_path: Optional[Path] = None
        self.auto_start_requested = bool(initial_wavefunction_path)
        self.generation_lock = threading.Lock()
        self.generate_button: Optional[ttk.Button] = None
        self.progress_bar: Optional[ttk.Progressbar] = None

        self.plotter = None
        self.nci_surface_actor = None
        self.live_update_after_id = None
        self.opacity_update_after_id = None
        self._workspace_restore_after_id = None
        self.plot_update_in_progress = False
        self._workspace_visible = True
        self.header_icon: Optional[tk.PhotoImage] = None
        self.viewer_controls_window: Optional[tk.Toplevel] = None
        self.overlay_process: Optional[subprocess.Popen] = None

        self.build_gui()
        if initial_wavefunction_path:
            self.set_wavefunction_path(initial_wavefunction_path)
        self.root.after(150, self.process_log_queue)
        self.start_multiwfn_locator()
        if self.auto_start_requested:
            self.root.after(900, self.auto_start_from_initial_wavefunction)

    def get_state(self) -> dict:
        names = (
            "wavefunction_path", "multiwfn_path", "rdg_isovalue", "opacity",
            "color_min", "color_max", "colormap", "show_molecule", "show_bonds",
            "show_scalar_bar", "background", "image_resolution", "command_template",
        )
        return {name: getattr(self, name).get() for name in names}

    def set_state(self, state: dict) -> None:
        allowed = set(self.get_state())
        for name, value in (state or {}).items():
            variable = getattr(self, name, None)
            if name in allowed and isinstance(variable, tk.Variable):
                variable.set(value)

    def load_config(self) -> dict:
        if CONFIG_FILE.exists():
            try:
                config = json.loads(CONFIG_FILE.read_text(encoding="utf-8"))
            except Exception:
                return {}
            template = str(config.get("multiwfn_template", "")).strip()
            if template == "q" or template == LEGACY_SAFE_MULTIWFN_TEMPLATE.strip():
                config["multiwfn_template"] = DEFAULT_MULTIWFN_TEMPLATE
            return config
        return {}

    def save_config(self) -> None:
        self.config["multiwfn_path"] = self.multiwfn_path.get()
        self.config["multiwfn_template"] = self.command_template.get()
        self.config["image_resolution"] = self.image_resolution.get()
        try:
            CONFIG_FILE.write_text(json.dumps(self.config, indent=2), encoding="utf-8")
        except Exception as exc:
            self.log(f"WARNING: Could not save config: {exc}")

    def selected_image_size(self) -> Optional[Tuple[int, int]]:
        return IMAGE_PRESETS.get(self.image_resolution.get(), IMAGE_PRESETS[DEFAULT_IMAGE_PRESET])

    def show_viewer_controls(self) -> None:
        """Show the persistent NCI controls beside an active PyVista view."""
        win = self.viewer_controls_window
        if win is None:
            return
        try:
            win.deiconify()
            win.attributes("-topmost", True)
            win.lift()
            win.focus_force()
        except tk.TclError:
            pass

    def schedule_live_plot_update(self, *_args) -> None:
        """Debounce control changes and refresh an already-open NCI scene."""
        if not self.is_plotter_alive() or self.rdg_cube is None or self.signrho_cube is None:
            return
        if self.live_update_after_id is not None:
            try:
                self.root.after_cancel(self.live_update_after_id)
            except tk.TclError:
                pass
        self.live_update_after_id = self.root.after(220, self._run_live_plot_update)

    def schedule_surface_opacity_update(self, *_args) -> None:
        """Debounce an actor-only opacity change; never rebuild the scene."""
        if self.opacity_update_after_id is not None:
            try:
                self.root.after_cancel(self.opacity_update_after_id)
            except tk.TclError:
                pass
        self.opacity_update_after_id = self.root.after(40, self._apply_surface_opacity)

    def apply_live_background(self, *_args) -> None:
        """Change renderer colors without rebuilding actors, lights, or camera."""
        if not self.is_plotter_alive():
            return
        try:
            bg_color = self.background.get()
            text_color = contrast_text_color(bg_color)
            try:
                self.plotter.set_background(
                    bg_color,
                    top=HQ_BACKGROUND_TOP.get(str(bg_color).strip().lower()),
                )
            except Exception:
                self.plotter.set_background(bg_color)
            if self.show_scalar_bar.get():
                set_scalar_bar_text_color(self.plotter, text_color, NCI_SCALAR_BAR_TITLE)
            self.plotter.render()
        except (AttributeError, RuntimeError, tk.TclError):
            return

    def _apply_surface_opacity(self) -> None:
        self.opacity_update_after_id = None
        if not self.is_plotter_alive() or self.nci_surface_actor is None:
            return
        try:
            opacity = max(0.05, min(1.0, float(self.opacity.get())))
            prop = self.nci_surface_actor.GetProperty()
            prop.SetOpacity(opacity)
            self.plotter.render()
        except (TypeError, ValueError, AttributeError, tk.TclError):
            # Partial text-entry values must leave the existing scene intact.
            return

    def _run_live_plot_update(self) -> None:
        self.live_update_after_id = None
        if not self.plot_update_in_progress:
            self.update_plot(live=True)

    def recent_wavefunction_files(self) -> list[str]:
        values = self.config.get("recent_wavefunction_files", [])
        if isinstance(values, list):
            return [str(item) for item in values if str(item).strip()][:MAX_RECENT_FILES]
        return []

    def remember_wavefunction_file(self, path: Path) -> None:
        clean = str(path)
        recent = [clean] + [
            item for item in self.recent_wavefunction_files()
            if os.path.normcase(item) != os.path.normcase(clean)
        ]
        self.config["recent_wavefunction_files"] = recent[:MAX_RECENT_FILES]
        try:
            self.wavefunction_combo.configure(values=self.config["recent_wavefunction_files"])
        except Exception:
            pass
        self.save_config()

    def start_multiwfn_locator(self) -> None:
        if self.multiwfn_path.get().strip():
            return

        def worker() -> None:
            found = find_multiwfn_deep()
            self.root.after(0, lambda: self.finish_multiwfn_locator(found))

        threading.Thread(target=worker, daemon=True).start()

    def finish_multiwfn_locator(self, found: Optional[str]) -> None:
        if found and not self.multiwfn_path.get().strip():
            self.multiwfn_path.set(found)
            self.save_config()
            if self.auto_start_requested:
                self.root.after(250, self.auto_start_from_initial_wavefunction)

    def auto_start_from_initial_wavefunction(self) -> None:
        if not self.auto_start_requested:
            return
        if not self.wavefunction_path.get().strip():
            return
        if not self.multiwfn_path.get().strip() and not find_multiwfn():
            self.log("Automatic NCI plotting is waiting for Multiwfn detection.")
            return
        self.auto_start_requested = False
        self.log("Automatic NCI workflow started from the selected wavefunction file.")
        self.start_generate_nci(auto_open=True)

    def build_gui(self) -> None:
        header = ttk.Frame(self.root, style="Header.TFrame", padding=(14, 10))
        if not self.embedded:
            header.pack(fill="x")
        self.header_icon = load_header_icon(NCI_ICON_PATH)
        if self.header_icon is not None:
            tk.Label(header, image=self.header_icon, bg="#1e3a5f", bd=0, highlightthickness=0).grid(row=0, column=0, rowspan=2, sticky="w", padx=(0, 10))
        ttk.Label(header, text="NCI Plotter", style="HeaderTitle.TLabel").grid(row=0, column=1, sticky="w")
        ttk.Label(
            header,
            text="Non-covalent interaction surfaces",
            style="HeaderSub.TLabel",
        ).grid(row=1, column=1, sticky="w")
        header.columnconfigure(2, weight=1)
        header_actions = ttk.Frame(header, style="Header.TFrame")
        header_actions.grid(row=0, column=3, rowspan=2, sticky="e")
        about_link = ttk.Label(header_actions, text="About", style="HeaderLink.TLabel", cursor="hand2")
        about_link.pack(side="right", padx=(12, 0))
        about_link.bind(
            "<Button-1>",
            lambda _event: open_about_dialog(self.root, "NCI Plotter", NCI_ICON_PATH, ABOUT_PURPOSE),
        )
        ttk.Button(
            header_actions,
            text="NCI + QTAIM overlay",
            command=self.open_nci_qtaim_overlay,
            style="HeaderCTA.TButton",
        ).pack(side="right")

        main_host = ttk.Frame(self.root, style="Panel.TFrame")
        main_host.pack(fill="both", expand=True)
        main_host.rowconfigure(0, weight=1)
        main_host.columnconfigure(0, weight=1)
        main_canvas = tk.Canvas(main_host, highlightthickness=0, borderwidth=0, bg="#f4f6f9")
        main_scroll = ttk.Scrollbar(main_host, orient="vertical", command=main_canvas.yview)
        main_canvas.configure(yscrollcommand=main_scroll.set)
        main_canvas.grid(row=0, column=0, sticky="nsew")
        main_scroll.grid(row=0, column=1, sticky="ns")

        main = ttk.Frame(main_canvas, style="Panel.TFrame", padding=10)
        main_window = main_canvas.create_window((0, 0), window=main, anchor="nw")
        main.bind("<Configure>", lambda _e: main_canvas.configure(scrollregion=main_canvas.bbox("all")))
        main_canvas.bind("<Configure>", lambda e: main_canvas.itemconfigure(main_window, width=e.width))
        bind_mousewheel_to_canvas(main_canvas, main)

        footer = ttk.Frame(self.root, style="Panel.TFrame", padding=(12, 6))
        footer.pack(side="bottom", fill="x")
        ttk.Label(footer, text=COPYRIGHT_NOTE, style="Muted.TLabel").pack(anchor="w")

        input_frame = ttk.LabelFrame(main, text="Input", padding=8)
        input_frame.pack(fill="x", pady=(0, 8))

        ttk.Label(input_frame, text="Wavefunction file:").grid(row=0, column=0, sticky="w")
        self.wavefunction_combo = ttk.Combobox(input_frame, textvariable=self.wavefunction_path, values=self.recent_wavefunction_files())
        keep_entry_end_visible(self.wavefunction_combo, self.wavefunction_path)
        self.wavefunction_combo.grid(row=0, column=1, sticky="ew", padx=5)
        self.wavefunction_combo.bind("<<ComboboxSelected>>", lambda _e: self.set_wavefunction_path(self.wavefunction_path.get().strip()))
        ttk.Button(input_frame, text="Browse", command=self.browse_wavefunction).grid(
            row=0, column=2, padx=5
        )
        if self.embedded:
            ttk.Button(
                input_frame,
                text="NCI + QTAIM overlay",
                command=self.open_nci_qtaim_overlay,
                style="HeaderCTA.TButton",
            ).grid(row=0, column=3, rowspan=2, sticky="e", padx=(18, 0))

        ttk.Label(input_frame, text="Output folder:").grid(
            row=1, column=0, sticky="w", pady=(6, 0)
        )
        output_entry = ttk.Entry(input_frame, textvariable=self.output_dir, state="readonly")
        keep_entry_end_visible(output_entry, self.output_dir)
        output_entry.grid(row=1, column=1, sticky="ew", padx=5, pady=(6, 0))

        input_frame.columnconfigure(1, weight=4)
        if self.embedded:
            input_frame.columnconfigure(3, weight=1)

        gen_frame = ttk.LabelFrame(main, text="NCI data generation", padding=8)
        gen_frame.pack(fill="x", pady=(0, 8))

        gen_buttons = ttk.Frame(gen_frame)
        gen_buttons.pack(fill="x")

        self.generate_button = ttk.Button(
            gen_buttons,
            text="Generate NCI data",
            command=self.start_generate_nci,
            style="Primary.TButton",
        )
        self.generate_button.pack(side="left", padx=(0, 6))

        ttk.Button(
            gen_buttons,
            text="Edit Multiwfn command template",
            command=self.edit_template_dialog,
        ).pack(side="left", padx=6)

        progress_row = ttk.Frame(gen_frame)
        progress_row.pack(fill="x", pady=(8, 0))
        ttk.Label(progress_row, textvariable=self.progress_status).pack(side="left")
        self.progress_bar = ttk.Progressbar(
            gen_frame,
            variable=self.progress_value,
            maximum=100.0,
            mode="determinate",
            style="Blue.Horizontal.TProgressbar",
        )
        self.progress_bar.pack(fill="x", pady=(4, 0))

        self.viewer_controls_window = tk.Toplevel(self.root)
        self.viewer_controls_window.title("NCI Viewer Controls")
        self.viewer_controls_window.geometry("370x650")
        self.viewer_controls_window.minsize(340, 560)
        configure_builder_ui_style(self.viewer_controls_window)
        self.viewer_controls_window.attributes("-topmost", True)
        self.viewer_controls_window.protocol("WM_DELETE_WINDOW", self.viewer_controls_window.withdraw)
        self.viewer_controls_window.withdraw()

        ttk.Button(
            main,
            text="Open viewer / visual controls",
            command=self.open_viewer_and_controls,
            style="Primary.TButton",
        ).pack(anchor="w", pady=(0, 8))

        control_frame = ttk.LabelFrame(
            self.viewer_controls_window,
            text="Visualization controls",
            padding=12,
        )
        control_frame.pack(fill="both", expand=True, padx=12, pady=12)
        control_frame.columnconfigure(0, weight=1)

        surface_frame = ttk.LabelFrame(control_frame, text="Surface", padding=8)
        surface_frame.grid(row=0, column=0, sticky="ew", pady=(0, 8))
        surface_frame.columnconfigure(0, weight=1)
        ttk.Label(surface_frame, text="RDG isovalue").grid(row=0, column=0, columnspan=2, sticky="w")
        ttk.Scale(
            surface_frame,
            from_=0.1,
            to=1.5,
            variable=self.rdg_isovalue,
            orient="horizontal",
            length=150,
        ).grid(row=1, column=0, sticky="ew", pady=(2, 0))

        ttk.Entry(surface_frame, textvariable=self.rdg_isovalue, width=9).grid(
            row=1, column=1, padx=(8, 0), pady=(2, 0)
        )

        ttk.Label(surface_frame, text="Opacity").grid(
            row=2, column=0, columnspan=2, sticky="w", pady=(8, 0)
        )
        ttk.Scale(
            surface_frame,
            from_=0.05,
            to=1.0,
            variable=self.opacity,
            orient="horizontal",
            length=150,
        ).grid(row=3, column=0, sticky="ew", pady=(2, 0))

        ttk.Entry(surface_frame, textvariable=self.opacity, width=9).grid(
            row=3, column=1, padx=(8, 0), pady=(2, 0)
        )

        color_frame = ttk.LabelFrame(control_frame, text="Colors", padding=8)
        color_frame.grid(row=1, column=0, sticky="ew", pady=(0, 8))
        color_frame.columnconfigure(1, weight=1)
        ttk.Label(color_frame, text="Color min").grid(row=0, column=0, sticky="w")
        ttk.Entry(color_frame, textvariable=self.color_min, width=12).grid(row=0, column=1, sticky="ew", padx=(8, 0))
        ttk.Label(color_frame, text="Color max").grid(row=1, column=0, sticky="w", pady=(6, 0))
        ttk.Entry(color_frame, textvariable=self.color_max, width=12).grid(row=1, column=1, sticky="ew", padx=(8, 0), pady=(6, 0))
        ttk.Label(color_frame, text="Colormap").grid(row=2, column=0, sticky="w", pady=(6, 0))
        ttk.Combobox(
            color_frame,
            textvariable=self.colormap,
            values=["bwr", "seismic", "coolwarm", "rainbow", "jet", "viridis", "plasma"],
            state="readonly",
        ).grid(row=2, column=1, sticky="ew", padx=(8, 0), pady=(6, 0))
        ttk.Label(color_frame, text="Background").grid(row=3, column=0, sticky="w", pady=(6, 0))
        ttk.Combobox(
            color_frame,
            textvariable=self.background,
            values=["white", "black", "gray", "lightgray"],
            state="readonly",
        ).grid(row=3, column=1, sticky="ew", padx=(8, 0), pady=(6, 0))

        display_frame = ttk.LabelFrame(control_frame, text="Display", padding=8)
        display_frame.grid(row=2, column=0, sticky="ew", pady=(0, 8))
        display_frame.columnconfigure(0, weight=1)
        ttk.Checkbutton(
            display_frame, text="Show molecule", variable=self.show_molecule
        ).grid(row=0, column=0, sticky="w")

        ttk.Checkbutton(
            display_frame, text="Show bonds", variable=self.show_bonds
        ).grid(row=1, column=0, sticky="w", pady=(4, 0))

        ttk.Checkbutton(
            display_frame, text="Show scalar bar", variable=self.show_scalar_bar
        ).grid(row=2, column=0, sticky="w", pady=(4, 0))

        ttk.Label(display_frame, text="Image size").grid(row=3, column=0, sticky="w", pady=(8, 0))
        ttk.Combobox(
            display_frame,
            textvariable=self.image_resolution,
            values=list(IMAGE_PRESETS.keys()),
            state="readonly",
        ).grid(row=4, column=0, sticky="ew", pady=(2, 0))

        button_row = ttk.Frame(control_frame)
        button_row.grid(row=3, column=0, sticky="ew")
        button_row.columnconfigure(0, weight=1)

        ttk.Button(button_row, text="Reset view", command=self.reset_view).grid(row=0, column=0, sticky="ew")
        ttk.Button(button_row, text="Save image", command=self.save_image).grid(row=1, column=0, sticky="ew", pady=(6, 0))

        for variable in (
            self.rdg_isovalue,
            self.color_min,
            self.color_max,
            self.colormap,
            self.show_molecule,
            self.show_bonds,
            self.show_scalar_bar,
        ):
            variable.trace_add("write", self.schedule_live_plot_update)
        self.background.trace_add("write", self.apply_live_background)
        self.opacity.trace_add("write", self.schedule_surface_opacity_update)

        log_frame = ttk.LabelFrame(main, text="Status / log", padding=8)
        log_frame.pack(fill="both", expand=True)

        self.log_text = tk.Text(log_frame, height=16, wrap="word", font=("Consolas", 10), relief="solid", bd=1)
        self.log_text.pack(side="left", fill="both", expand=True)

        scrollbar = ttk.Scrollbar(log_frame, orient="vertical", command=self.log_text.yview)
        scrollbar.pack(side="right", fill="y")
        self.log_text.configure(yscrollcommand=scrollbar.set)

        self.log("NCI Plotter started.")
        self.log("Select a .wfn or .wfx file.")
        self.log("The script will call Multiwfn to generate the real RDG and sign(lambda2)rho cube files automatically.")

    def log(self, text: str) -> None:
        timestamp = time.strftime("%H:%M:%S")
        self.log_queue.put(f"[{timestamp}] {text}\n")

    def process_log_queue(self) -> None:
        while True:
            try:
                msg = self.log_queue.get_nowait()
            except queue.Empty:
                break
            self.log_text.insert("end", msg)
            self.log_text.see("end")
        self.root.after(150, self.process_log_queue)

    def set_progress(self, percent: float, status: Optional[str] = None, allow_decrease: bool = False) -> None:
        def apply() -> None:
            value = max(0.0, min(100.0, float(percent)))
            if not allow_decrease:
                value = max(self.progress_percent_value, value)
            self.progress_percent_value = value
            self.progress_value.set(value)
            if status is not None:
                self.progress_status.set(f"Status: {status} ({value:5.1f} %)")

        self.root.after(0, apply)

    @staticmethod
    def format_elapsed(seconds: float) -> str:
        elapsed = max(0, int(seconds))
        hh = elapsed // 3600
        mm = (elapsed % 3600) // 60
        ss = elapsed % 60
        return f"{hh:02d}:{mm:02d}:{ss:02d}"

    @staticmethod
    def estimated_cube_generation_progress(elapsed_seconds: float) -> float:
        return min(88.0, 25.0 + max(0.0, elapsed_seconds) * 0.7)

    def browse_wavefunction(self) -> None:
        path = filedialog.askopenfilename(
            title="Select wavefunction file",
            filetypes=[
                ("Wavefunction files", "*.wfn *.wfx"),
                ("Rejected ORCA output", "*.out *.log"),
                ("All files", "*.*"),
            ],
        )
        if not path:
            return

        self.set_wavefunction_path(path)
        self.root.after(100, lambda: self.start_generate_nci(auto_open=True))

    def set_wavefunction_path(self, path: str) -> None:
        p = Path(path)
        ext = p.suffix.lower()

        if ext in REJECTED_EXTS:
            messagebox.showerror(
                "Unsupported input",
                "ORCA .out/.log files are not valid NCI inputs.\n\n"
                "NCI analysis requires wavefunction/electron-density information.\n"
                "Please use .wfn or .wfx generated from ORCA, for example using orca_2aim.",
            )
            return

        if ext not in SUPPORTED_WAVEFUNCTION_EXTS:
            messagebox.showerror(
                "Unsupported input",
                f"Unsupported file type: {ext}\n\nUse .wfn or .wfx.",
            )
            return

        self.wavefunction_path.set(str(p))
        self.remember_wavefunction_file(p)
        outdir = p.with_suffix("")
        outdir = outdir.parent / f"{outdir.name}_NCI"
        self.output_dir.set(str(outdir))
        self.log(f"Selected wavefunction file: {p}")

    def prompt_for_multiwfn(self) -> Optional[str]:
        path = filedialog.askopenfilename(
            title="Select Multiwfn executable",
            filetypes=executable_filetypes("Executable files"),
            parent=self.root,
        )
        if path:
            self.multiwfn_path.set(path)
            self.save_config()
            self.log(f"Selected Multiwfn executable: {path}")
            return path
        return None

    def ensure_multiwfn_available(self) -> Path:
        raw = self.multiwfn_path.get().strip()
        if raw:
            candidate = Path(raw)
            if candidate.exists():
                return candidate
            found = shutil.which(raw)
            if found:
                self.multiwfn_path.set(found)
                self.save_config()
                return Path(found)

        messagebox.showwarning(
            "Multiwfn not found",
            "Multiwfn was not found automatically. Please select the Multiwfn executable.",
            parent=self.root,
        )
        selected = self.prompt_for_multiwfn()
        if selected:
            candidate = Path(selected)
            if candidate.exists():
                return candidate
            found = shutil.which(selected)
            if found:
                self.multiwfn_path.set(found)
                self.save_config()
                return Path(found)
        raise FileNotFoundError("Multiwfn executable was not selected or could not be found.")

    def validate_generation_inputs(self) -> tuple[Path, Path, Path]:
        wf = Path(self.wavefunction_path.get().strip())

        if self.output_dir.get().strip():
            outdir = Path(self.output_dir.get().strip())
        else:
            outdir = wf.with_suffix("").parent / f"{wf.stem}_NCI"

        if not wf.exists():
            raise FileNotFoundError("No valid wavefunction file selected.")

        if wf.suffix.lower() in REJECTED_EXTS:
            raise ValueError("ORCA .out/.log files are not valid NCI inputs. Use .wfn or .wfx.")

        if wf.suffix.lower() not in SUPPORTED_WAVEFUNCTION_EXTS:
            raise ValueError(f"Unsupported wavefunction file type: {wf.suffix}")

        mwfn = self.ensure_multiwfn_available()

        return wf, mwfn, outdir

    def start_generate_nci(self, auto_open: bool = False) -> None:
        try:
            wf, mwfn, outdir = self.validate_generation_inputs()
        except Exception as exc:
            messagebox.showerror("Input error", str(exc))
            self.log(f"ERROR: {exc}")
            return

        if not self.generation_lock.acquire(blocking=False):
            self.log("NCI generation is already running. Waiting for the current Multiwfn job to finish.")
            return

        self.save_config()
        self.rdg_cube = None
        self.signrho_cube = None
        self.rdg_cube_path = None
        self.signrho_cube_path = None
        self.set_progress(0.0, "Starting NCI generation", allow_decrease=True)
        if self.generate_button is not None:
            self.generate_button.configure(state="disabled")
        thread = threading.Thread(
            target=self.generate_nci_worker,
            args=(wf, mwfn, outdir, auto_open),
            daemon=True,
        )
        thread.start()

    def _prepare_multiwfn_batch_input(self, template_text: str) -> tuple[str, list[str]]:
        commands: list[str] = []
        for raw_line in template_text.splitlines():
            line = raw_line.strip()
            if not line:
                continue
            if line.startswith("#"):
                continue
            commands.append(line)

        if not commands:
            raise RuntimeError(
                "The Multiwfn command template does not contain any executable commands after removing comments."
            )

        # Multiwfn may pause at startup with 'Press ENTER button to continue'
        # before showing the main menu. A leading blank line safely satisfies
        # that prompt without changing the subsequent command sequence.
        batch_text = "\n" + "\n".join(commands) + "\n"
        return batch_text, commands

    def prepare_wavefunction_for_multiwfn(self, wf: Path, outdir: Path) -> Path:
        if wf.suffix.lower() != ".wfn":
            return wf

        lines = wf.read_text(encoding="utf-8", errors="replace").splitlines()
        changed = 0
        prepared_lines: list[str] = []
        centre_line_re = re.compile(r"^(\s*)(\S+)(\s+\(CENTRE\s+\d+\).*)$", re.IGNORECASE)

        for line in lines:
            match = centre_line_re.match(line)
            if not match or "CHARGE" not in line.upper():
                prepared_lines.append(line)
                continue

            leading, label, rest = match.groups()
            symbol = element_symbol_from_wfn_label(label)
            if symbol and symbol != label:
                prepared_lines.append(f"{leading}{symbol:<{len(label)}}{rest}")
                changed += 1
            else:
                prepared_lines.append(line)

        if not changed:
            return wf

        prepared = outdir / f"{wf.stem}_multiwfn_labels.wfn"
        prepared.write_text("\n".join(prepared_lines) + "\n", encoding="utf-8")
        self.log(
            f"Prepared Multiwfn-compatible WFN copy with simplified atom labels: {prepared} "
            f"({changed} label(s) adjusted; original file unchanged)."
        )
        return prepared

    def generate_nci_worker(self, wf: Path, mwfn: Path, outdir: Path, auto_open: bool = False) -> None:
        try:
            self.set_progress(5.0, "Preparing output folder")
            outdir.mkdir(parents=True, exist_ok=True)
            self.output_dir.set(str(outdir))

            self.log(f"Output folder: {outdir}")

            self.set_progress(8.0, "Checking for existing cube files")
            existing_rdg, existing_signrho = self.detect_nci_cubes(outdir)
            if not (existing_rdg and existing_signrho) and wf.parent != outdir:
                existing_rdg, existing_signrho = self.detect_nci_cubes(wf.parent)
                if existing_rdg and existing_signrho:
                    self.output_dir.set(str(wf.parent))
            if existing_rdg and existing_signrho:
                self.set_progress(80.0, "Reusing existing cube files")
                self.log("Existing NCI cube files were found in the output folder.")
                self.log(f"Reusing RDG cube: {existing_rdg}")
                self.log(f"Reusing sign(lambda2)rho cube: {existing_signrho}")
                self.root.after(0, self.load_cubes_and_plot)
                return

            self.set_progress(12.0, "Preparing Multiwfn batch input")
            self.log("No existing NCI cube pair was found. Running Multiwfn to generate them.")

            template_text = self.command_template.get()
            if not template_text.strip():
                raise RuntimeError("Multiwfn command template is empty.")

            batch_text, commands = self._prepare_multiwfn_batch_input(template_text)

            if commands == ["q"]:
                raise RuntimeError(
                    "The saved Multiwfn command template contains only 'q', so Multiwfn exits immediately. "
                    "Open 'Edit Multiwfn command template' and click 'Reset default', or restart the script to reload the upgraded default template."
                )

            self.log("Using Multiwfn NCI route from the command template.")
            self.log("Default 2026.x route is: 20 -> 1 -> 3 -> 3 -> 0 -> q.")
            self.log("Expected files: func1.cub = sign(lambda2)rho; func2.cub = RDG.")
            self.log("Comment lines are stripped before execution.")
            self.log("A leading ENTER is added automatically for the initial Multiwfn startup prompt.")

            script_path = outdir / "multiwfn_nci_input.txt"
            script_path.write_text(batch_text, encoding="utf-8")
            stdout_path = outdir / "multiwfn_stdout.txt"
            stderr_path = outdir / "multiwfn_stderr.txt"

            self.set_progress(16.0, "Preparing wavefunction for Multiwfn")
            multiwfn_wf = self.prepare_wavefunction_for_multiwfn(wf, outdir)

            self.set_progress(20.0, "Starting Multiwfn cube generation")
            self.log("Running Multiwfn in batch mode...")
            self.log(f"Command script: {script_path}")
            self.log("Effective command sequence: " + " -> ".join(commands))

            cmd = [str(mwfn), str(multiwfn_wf)]

            with script_path.open("r", encoding="utf-8") as stdin:
                with stdout_path.open("w", encoding="utf-8", errors="replace") as stdout_file, stderr_path.open(
                    "w", encoding="utf-8", errors="replace"
                ) as stderr_file:
                    proc = subprocess.Popen(
                        cmd,
                        stdin=stdin,
                        stdout=stdout_file,
                        stderr=stderr_file,
                        cwd=str(outdir),
                        text=True,
                        shell=False,
                    )
                    started = time.monotonic()
                    while True:
                        code = proc.poll()
                        elapsed = time.monotonic() - started
                        self.set_progress(
                            self.estimated_cube_generation_progress(elapsed),
                            f"Generating NCI cubes with Multiwfn, elapsed {self.format_elapsed(elapsed)}",
                        )
                        if code is not None:
                            break
                        time.sleep(1.0)

            self.set_progress(88.0, "Multiwfn finished")
            self.log("Multiwfn finished.")
            self.log(f"Multiwfn stdout saved to: {stdout_path}")
            self.log(f"Multiwfn stderr saved to: {stderr_path}")

            self.set_progress(90.0, "Detecting generated cube files")
            rdg, signrho = self.detect_nci_cubes(outdir)

            if proc.returncode != 0:
                if rdg and signrho:
                    self.log(
                        f"WARNING: Multiwfn exited with return code {proc.returncode}, "
                        "but the required NCI cube files were generated successfully."
                    )
                    self.log("Continuing with the generated cubes.")
                else:
                    self.log(f"ERROR: Multiwfn failed with return code {proc.returncode}.")
                    self.log(f"See: {stdout_path}")
                    self.log(f"See: {stderr_path}")
                    raise RuntimeError("Multiwfn failed. Check the log files in the output folder.")

            if not rdg or not signrho:
                self.log("ERROR: Could not automatically identify RDG and sign(lambda2)rho cube files.")
                raise RuntimeError(
                    "Expected NCI cube files were not detected automatically. "
                    "The Multiwfn command template likely needs adjustment for your Multiwfn version."
                )

            self.log(f"Detected RDG cube: {rdg}")
            self.log(f"Detected sign(lambda2)rho cube: {signrho}")

            self.root.after(0, self.load_cubes_and_plot)

        except Exception as exc:
            self.set_progress(0.0, "Generation failed", allow_decrease=True)
            self.log(f"ERROR: {exc}")
            self.root.after(0, lambda e=exc: messagebox.showerror("NCI generation failed", str(e)))
        finally:
            self.generation_lock.release()
            if self.generate_button is not None:
                self.root.after(0, lambda: self.generate_button.configure(state="normal"))

    def detect_nci_cubes(self, outdir: Path) -> tuple[Optional[Path], Optional[Path]]:
        cube_files = list(outdir.glob("*.cube")) + list(outdir.glob("*.cub"))

        # Multiwfn NCI post-processing convention:
        #   func1.cub = sign(lambda2)rho
        #   func2.cub = RDG
        func1 = outdir / "func1.cub"
        func2 = outdir / "func2.cub"

        if func1.exists() and func2.exists():
            return func2, func1

        func1_cube = outdir / "func1.cube"
        func2_cube = outdir / "func2.cube"

        if func1_cube.exists() and func2_cube.exists():
            return func2_cube, func1_cube

        rdg_candidates = []
        signrho_candidates = []

        for f in cube_files:
            name = f.name.lower()

            if "rdg" in name or "reduced" in name or "grad" in name:
                rdg_candidates.append(f)

            if (
                "sign" in name
                or "lambda" in name
                or "lambda2" in name
                or "rho" in name
                or "sl2r" in name
            ):
                signrho_candidates.append(f)

        rdg = rdg_candidates[0] if rdg_candidates else None
        signrho = signrho_candidates[0] if signrho_candidates else None

        if rdg and signrho and rdg == signrho:
            signrho = None

        return rdg, signrho

    def load_cubes_and_plot(self) -> None:
        try:
            self.set_progress(92.0, "Loading cube files")
            rdg_path, signrho_path = self.detect_nci_cubes(Path(self.output_dir.get().strip()))
            if rdg_path is None or signrho_path is None:
                raise FileNotFoundError(
                    "Could not find generated RDG and sign(lambda2)rho cube files in the output folder."
                )

            if not rdg_path.exists():
                raise FileNotFoundError(f"RDG cube file not found: {rdg_path}")

            if not signrho_path.exists():
                raise FileNotFoundError(f"sign(lambda2)rho cube file not found: {signrho_path}")

            self.log("Loading cube files...")
            self.rdg_cube = CubeParser.parse(rdg_path)
            self.signrho_cube = CubeParser.parse(signrho_path)
            self.rdg_cube_path = rdg_path
            self.signrho_cube_path = signrho_path

            if self.rdg_cube.shape != self.signrho_cube.shape:
                raise CubeParseError(
                    f"Cube grid shape mismatch: RDG {self.rdg_cube.shape}, "
                    f"sign(lambda2)rho {self.signrho_cube.shape}"
                )

            self.log(f"Loaded RDG cube: {rdg_path}")
            self.log(f"Loaded sign(lambda2)rho cube: {signrho_path}")
            self.set_progress(96.0, "Rendering NCI plot")
            self.update_plot()
            self.set_progress(100.0, "Ready")

        except Exception as exc:
            self.set_progress(0.0, "Cube loading failed", allow_decrease=True)
            self.log(f"ERROR: {exc}")
            messagebox.showerror("Cube loading failed", str(exc))

    def make_uniform_grid(self):
        try:
            import pyvista as pv
        except Exception as exc:
            raise RuntimeError("PyVista/VTK is not installed. Install with: pip install pyvista") from exc

        if self.rdg_cube is None or self.signrho_cube is None:
            raise RuntimeError("Cube data not loaded.")

        rdg = self.rdg_cube
        signrho = self.signrho_cube

        spacing = np.array(
            [
                np.linalg.norm(rdg.axes[0]),
                np.linalg.norm(rdg.axes[1]),
                np.linalg.norm(rdg.axes[2]),
            ],
            dtype=float,
        )

        diagonal_axes = np.diag(np.diag(rdg.axes))
        if not np.allclose(rdg.axes, diagonal_axes, atol=1e-6):
            self.log("WARNING: Non-orthogonal cube grid detected. PyVista ImageData assumes orthogonal axes.")

        try:
            grid = pv.ImageData()
        except AttributeError:
            grid = pv.UniformGrid()

        grid.dimensions = np.array(rdg.shape) + 1
        grid.origin = tuple(float(x) for x in rdg.origin)
        grid.spacing = tuple(float(x) for x in spacing)

        rdg_values = rdg.values.ravel(order="F")
        signrho_values = signrho.values.ravel(order="F")

        grid.cell_data["RDG"] = rdg_values
        grid.cell_data[NCI_SCALAR_NAME] = signrho_values

        return grid

    def is_plotter_alive(self) -> bool:
        if self.plotter is None:
            return False

        try:
            if bool(getattr(self.plotter, "_closed", False)):
                return False

            if getattr(self.plotter, "render_window", None) is None:
                return False

            iren = getattr(self.plotter, "iren", None)
            if iren is None:
                return False

            if hasattr(self.plotter, "closed") and self.plotter.closed:
                return False

            vtk_interactor = getattr(iren, "interactor", None)
            if vtk_interactor is None:
                return False
            get_done = getattr(vtk_interactor, "GetDone", None)
            if callable(get_done) and bool(get_done()):
                return False
            get_initialized = getattr(vtk_interactor, "GetInitialized", None)
            if callable(get_initialized) and not bool(get_initialized()):
                return False

            render_window = self.plotter.render_window
            get_mapped = getattr(render_window, "GetMapped", None)
            if callable(get_mapped) and not bool(get_mapped()):
                return False

            return True

        except Exception:
            return False

    def on_show(self) -> None:
        """Restore a released viewer directly from already-loaded cube data."""
        self._workspace_visible = True
        if (
            self.embedded
            and self.rdg_cube is not None
            and self.signrho_cube is not None
            and not self.is_plotter_alive()
            and self._workspace_restore_after_id is None
        ):
            self._workspace_restore_after_id = self.root.after_idle(self._restore_workspace_plot)

    def _restore_workspace_plot(self) -> None:
        self._workspace_restore_after_id = None
        if self._workspace_visible and not self.is_plotter_alive():
            self.log("Restoring NCI viewer from loaded cube data.")
            self.update_plot()

    def on_hide(self) -> None:
        """Release VTK resources before another embedded visualizer starts."""
        self._workspace_visible = False
        if self._workspace_restore_after_id is not None:
            try:
                self.root.after_cancel(self._workspace_restore_after_id)
            except tk.TclError:
                pass
            self._workspace_restore_after_id = None
        if self.live_update_after_id is not None:
            try:
                self.root.after_cancel(self.live_update_after_id)
            except tk.TclError:
                pass
            self.live_update_after_id = None
        if self.opacity_update_after_id is not None:
            try:
                self.root.after_cancel(self.opacity_update_after_id)
            except tk.TclError:
                pass
            self.opacity_update_after_id = None
        self.close_dead_plotter_reference()
        if self.viewer_controls_window is not None:
            try:
                self.viewer_controls_window.withdraw()
            except tk.TclError:
                pass

    def close_dead_plotter_reference(self) -> None:
        if self.plotter is None:
            return

        try:
            self.plotter.close()
        except Exception:
            pass

        self.plotter = None
        self.nci_surface_actor = None

    def update_plot(self, live: bool = False) -> None:
        if self.embedded and not self._workspace_visible:
            return
        if self.plot_update_in_progress:
            return
        self.plot_update_in_progress = True
        try:
            import pyvista as pv
        except Exception as exc:
            if not live:
                messagebox.showerror(
                    "PyVista missing",
                    f"PyVista/VTK is not installed.\n\nInstall with:\n{sys.executable} -m pip install pyvista",
                )
            self.log(f"ERROR: PyVista/VTK not installed: {exc}")
            self.plot_update_in_progress = False
            return

        try:
            if self.rdg_cube is None or self.signrho_cube is None:
                if self.generation_lock.locked():
                    self.log("NCI generation is still running. The plot will be available after Multiwfn finishes.")
                    return

                output_text = self.output_dir.get().strip()
                if not output_text:
                    self.log("No NCI cube files loaded yet. Select a WFN/WFX file and click 'Generate NCI data'.")
                    return

                rdg_path, signrho_path = self.detect_nci_cubes(Path(output_text))

                if rdg_path is not None and signrho_path is not None:
                    self.rdg_cube = CubeParser.parse(Path(rdg_path))
                    self.signrho_cube = CubeParser.parse(Path(signrho_path))
                else:
                    self.log(
                        "No generated NCI cube pair found yet. "
                        "Click 'Generate NCI data' or select a folder that already contains RDG and sign(lambda2)rho cubes."
                    )
                    return

            isovalue = float(self.rdg_isovalue.get())
            opacity = float(self.opacity.get())
            clim_min = float(self.color_min.get())
            clim_max = float(self.color_max.get())

            if clim_min >= clim_max:
                raise ValueError("Color scale minimum must be smaller than maximum.")

            grid = self.make_uniform_grid()
            # Convert cell data to point data for contour operation
            grid = grid.cell_data_to_point_data()
            surface = grid.contour(isosurfaces=[isovalue], scalars="RDG")
            sampled = surface.sample(grid)

            if sampled.n_points == 0:
                raise RuntimeError(
                    f"No RDG isosurface found at isovalue {isovalue}. "
                    "Try a different RDG isovalue."
                )

            reuse_plotter = self.is_plotter_alive()
            camera_position = None
            if reuse_plotter:
                try:
                    camera_position = self.plotter.camera_position
                except Exception:
                    camera_position = None
                self.plotter.clear()
                self.nci_surface_actor = None
            else:
                self.close_dead_plotter_reference()

            bounds = sampled.bounds
            extent = float(np.linalg.norm([bounds[1] - bounds[0], bounds[3] - bounds[2], bounds[5] - bounds[4]]))
            tiled_layout = None
            if not reuse_plotter:
                tiled_layout = compute_visualization_layout(
                    self.root,
                    control_width=370,
                    control_height=650,
                )
                self.plotter = pv.Plotter(window_size=tiled_layout.viewer_size)
                place_visualization_windows(self.viewer_controls_window, self.plotter, tiled_layout)
            bg_color = self.background.get()
            text_color = contrast_text_color(bg_color)
            try:
                self.plotter.set_background(bg_color, top=HQ_BACKGROUND_TOP.get(str(bg_color).strip().lower()))
            except Exception:
                self.plotter.set_background(bg_color)
            try:
                self.plotter.enable_depth_peeling(number_of_peels=8, occlusion_ratio=0.0)
            except Exception:
                pass
            try:
                self.plotter.renderer.SetTwoSidedLighting(True)
            except Exception:
                pass

            scalar_bar_args = {
                "title": NCI_SCALAR_BAR_TITLE,
                "vertical": True,
                "position_x": 0.86,
                "position_y": 0.15,
                "height": 0.7,
                "width": 0.08,
                "color": text_color,
                "title_font_size": 16,
                "label_font_size": 12,
            }

            self.nci_surface_actor = self.plotter.add_mesh(
                sampled,
                scalars=NCI_SCALAR_NAME,
                cmap=self.colormap.get(),
                clim=[clim_min, clim_max],
                opacity=opacity,
                smooth_shading=False,
                scalar_bar_args=scalar_bar_args if self.show_scalar_bar.get() else None,
                show_scalar_bar=self.show_scalar_bar.get(),
            )
            if self.show_scalar_bar.get():
                set_scalar_bar_text_color(self.plotter, text_color, NCI_SCALAR_BAR_TITLE)

            if self.show_molecule.get():
                # Molecule actors stay fully opaque in the main scene.  The
                # opacity setting belongs only to the NCI surface actor above.
                self.add_molecule_to_plotter(self.plotter)

            if camera_position is None:
                self.plotter.reset_camera()
            else:
                try:
                    self.plotter.camera_position = camera_position
                except Exception:
                    self.plotter.reset_camera()
            if reuse_plotter:
                self.plotter.render()
            else:
                place_visualization_windows(self.viewer_controls_window, self.plotter, tiled_layout)
                bring_pyvista_window_to_front(self.plotter)
                self.plotter.show(interactive_update=True, auto_close=False)
                place_visualization_windows(self.viewer_controls_window, self.plotter, tiled_layout)
                bring_pyvista_window_to_front(self.plotter, delay_s=0.05)
                self.root.after(
                    120,
                    lambda: place_visualization_windows(self.viewer_controls_window, self.plotter, tiled_layout),
                )
                self.root.after(180, self.show_viewer_controls)

            if not live:
                self.log("Plot updated.")

        except Exception as exc:
            if live:
                self.log(f"Live plot update skipped: {exc}")
            else:
                self.log(f"ERROR: {exc}")
                messagebox.showerror("Plot update failed", str(exc))
        finally:
            self.plot_update_in_progress = False

    def add_molecule_to_plotter(self, plotter) -> None:
        try:
            import pyvista as pv
        except Exception:
            return

        if self.rdg_cube is None:
            return

        atoms = self.rdg_cube.atom_coords
        numbers = self.rdg_cube.atom_numbers

        if atoms is None or len(atoms) == 0:
            self.log("No atom coordinates found in cube file.")
            return

        if self.show_bonds.get():
            bonds = self.guess_bonds(numbers, atoms)

            for i, j in bonds:
                p1 = np.asarray(atoms[i], dtype=float)
                p2 = np.asarray(atoms[j], dtype=float)
                midpoint = (p1 + p2) / 2.0

                for a, b, color in (
                    (p1, midpoint, self.bond_end_color(numbers[i])),
                    (midpoint, p2, self.bond_end_color(numbers[j])),
                ):
                    direction = b - a
                    length = float(np.linalg.norm(direction))

                    if length <= 0:
                        continue

                    cylinder = pv.Cylinder(
                        center=tuple(float(x) for x in (a + b) / 2.0),
                        direction=tuple(float(x) for x in direction / length),
                        radius=0.075,
                        height=length,
                        resolution=HQ_BOND_RESOLUTION,
                        capping=True,
                    )
                    self.add_molecule_mesh(plotter, cylinder, color)

        for number, coord in zip(numbers, atoms):
            radius = self.atom_display_radius(number)
            sphere = pv.Sphere(
                radius=radius,
                center=tuple(float(x) for x in coord),
                theta_resolution=HQ_ATOM_RESOLUTION,
                phi_resolution=HQ_ATOM_RESOLUTION,
            )
            self.add_molecule_mesh(plotter, sphere, self.atom_color(number))

    def add_molecule_mesh(self, plotter, mesh, color: str) -> None:
        add_mesh_safe(plotter, mesh, color=color, opacity=1.0, **molecule_material_parameters())

    def atom_display_radius(self, atomic_number: int) -> float:
        radius = self.covalent_radius(atomic_number) * 0.42
        return float(np.clip(radius, 0.16, 0.55))

    def atom_color(self, atomic_number: int) -> str:
        return ATOM_COLORS.get(atomic_number, "#E95FA5")

    def bond_end_color(self, atomic_number: int) -> str:
        return "#8E8E8E" if int(atomic_number) in {1, 6} else self.atom_color(atomic_number)

    def covalent_radius(self, atomic_number: int) -> float:
        return COVALENT_RADII.get(atomic_number, 0.77)

    def guess_bonds(self, numbers: list[int], coords: np.ndarray) -> list[tuple[int, int]]:
        bonds = []
        n = len(numbers)

        for i in range(n):
            for j in range(i + 1, n):
                dist = float(np.linalg.norm(coords[i] - coords[j]))
                cutoff = 1.20 * (
                    self.covalent_radius(numbers[i]) + self.covalent_radius(numbers[j])
                )

                if 0.35 < dist < cutoff:
                    bonds.append((i, j))

        return bonds

    def reset_view(self) -> None:
        if self.rdg_cube is None or self.signrho_cube is None:
            self.log("No plot data loaded yet. Generate NCI data first.")
            return

        # Restore default visualization settings
        self.rdg_isovalue.set(0.50)
        self.opacity.set(0.75)
        self.color_min.set("-0.05")
        self.color_max.set("0.05")
        self.colormap.set("rainbow")
        self.show_molecule.set(True)
        self.show_bonds.set(True)
        self.show_scalar_bar.set(True)
        self.background.set("black")

        self.log("Reset view: restored default visualization settings and redrawing clean plot window.")
        self.close_dead_plotter_reference()
        self.update_plot()

    def save_image(self) -> None:
        if not self.is_plotter_alive():
            messagebox.showerror("No plot", "No active PyVista plot to save. Generate NCI data or use Reset view to reopen it.")
            return

        path = filedialog.asksaveasfilename(
            title="Save image",
            defaultextension=".png",
            filetypes=[("PNG image", "*.png"), ("All files", "*.*")],
        )

        if not path:
            return

        try:
            image_size = self.selected_image_size()
            if image_size:
                save_pyvista_screenshot(self.plotter, path, self.background.get(), window_size=image_size, scale=1)
            else:
                save_pyvista_screenshot(self.plotter, path, self.background.get())
            self.save_config()
            self.log(f"Image saved: {path}")
        except Exception as exc:
            self.log(f"ERROR: Could not save image: {exc}")
            messagebox.showerror("Save failed", str(exc))

    def open_nci_qtaim_overlay(self) -> None:
        try:
            self._open_nci_qtaim_overlay()
        except Exception as exc:
            self.overlay_process = None
            message = f"Could not prepare NCI + QTAIM overlay: {type(exc).__name__}: {exc}"
            self.log(f"ERROR: {message}")
            messagebox.showerror("Overlay failed", message, parent=self.root)

    def _open_nci_qtaim_overlay(self) -> None:
        if self.overlay_process is not None and self.overlay_process.poll() is None:
            self.log("NCI + QTAIM overlay is already open.")
            return

        overlay_script = TOOLS_ROOT / "NCI_QTAIM_overlay" / "nci_qtaim_overlay.py"
        command = [sys.executable, str(overlay_script)]

        wavefunction = self.wavefunction_path.get().strip()
        qtaim_cp_file = None
        qtaim_path_file = None
        if wavefunction and Path(wavefunction).is_file():
            command.append(wavefunction)
            try:
                overlay_module_path = overlay_script
                import importlib.util
                spec = importlib.util.spec_from_file_location("crystengkit_overlay_probe", str(overlay_module_path))
                if spec is not None and spec.loader is not None:
                    overlay_probe = importlib.util.module_from_spec(spec)
                    sys.modules[spec.name] = overlay_probe
                    spec.loader.exec_module(overlay_probe)
                    qtaim_cp_file = overlay_probe.find_qtaim_cp_file(Path(wavefunction).parent, Path(wavefunction).stem)
                    qtaim_path_file = overlay_probe.find_qtaim_path_file(Path(wavefunction).parent, Path(wavefunction).stem)
            except Exception as exc:
                self.log(f"WARNING: QTAIM overlay file discovery failed: {exc}")
                qtaim_cp_file = None
                qtaim_path_file = None
        if qtaim_cp_file is not None:
            command.extend(["--cp", str(qtaim_cp_file)])
        if qtaim_path_file is not None:
            command.extend(["--paths", str(qtaim_path_file)])
        if self.rdg_cube_path and self.rdg_cube_path.is_file():
            command.extend(["--rdg", str(self.rdg_cube_path)])
        if self.signrho_cube_path and self.signrho_cube_path.is_file():
            command.extend(["--signrho", str(self.signrho_cube_path)])
        image_size = self.selected_image_size()
        if image_size is None and self.is_plotter_alive():
            try:
                image_size = tuple(int(v) for v in self.plotter.window_size)
            except Exception:
                image_size = None
        if image_size:
            command.extend(["--image-width", str(image_size[0]), "--image-height", str(image_size[1])])
        command.extend(
            [
                "--rdg-isovalue", str(float(self.rdg_isovalue.get())),
                "--opacity", str(float(self.opacity.get())),
                "--color-min", str(self.color_min.get()),
                "--color-max", str(self.color_max.get()),
                "--colormap", str(self.colormap.get()),
                "--background", str(self.background.get()),
                "--show-molecule", "1" if bool(self.show_molecule.get()) else "0",
                "--show-nci", "1",
            ]
        )

        try:
            log_dir = Path(self.output_dir.get().strip()) if self.output_dir.get().strip() else overlay_script.parent
            log_dir.mkdir(parents=True, exist_ok=True)
            launch_log = log_dir / "nci_qtaim_overlay.log"
            with launch_log.open("w", encoding="utf-8", errors="replace") as log_file:
                self.overlay_process = subprocess.Popen(
                    command,
                    cwd=str(overlay_script.parent),
                    stdout=log_file,
                    stderr=subprocess.STDOUT,
                )
            threading.Thread(
                target=self._monitor_overlay_process,
                args=(self.overlay_process, launch_log),
                daemon=True,
            ).start()
            self.log("Opened NCI + QTAIM overlay.")
            self.log(f"Overlay process log: {launch_log}")
        except Exception as exc:
            self.overlay_process = None
            self.log(f"ERROR: Could not open NCI + QTAIM overlay: {exc}")
            messagebox.showerror("Overlay failed", str(exc))

    def _monitor_overlay_process(self, process: subprocess.Popen, launch_log: Path) -> None:
        returncode = process.wait()

        def finish() -> None:
            if self.overlay_process is process:
                self.overlay_process = None
            if returncode == 0:
                self.log("NCI + QTAIM overlay closed.")
                return
            try:
                detail = launch_log.read_text(encoding="utf-8", errors="replace").strip()[-3000:]
            except OSError:
                detail = ""
            message = f"Overlay process failed with exit code {returncode}."
            if detail:
                message += f"\n\n{detail}"
            self.log(f"ERROR: {message}")
            messagebox.showerror("Overlay failed", message, parent=self.root)

        try:
            self.root.after(0, finish)
        except tk.TclError:
            pass

    def viewer_controls_are_visible(self) -> bool:
        win = self.viewer_controls_window
        if win is None:
            return False
        try:
            return bool(win.winfo_exists() and win.state() != "withdrawn" and win.winfo_viewable())
        except tk.TclError:
            return False

    def open_viewer_and_controls(self) -> None:
        """Open only the missing parts of the NCI viewer/control pair."""
        viewer_open = self.is_plotter_alive()
        controls_open = self.viewer_controls_are_visible()

        if not viewer_open:
            if self.rdg_cube is not None and self.signrho_cube is not None:
                self.log("Reopening PyVista viewer from loaded NCI cube data.")
                self.update_plot()
            else:
                output_text = self.output_dir.get().strip()
                rdg_path = signrho_path = None
                if output_text:
                    rdg_path, signrho_path = self.detect_nci_cubes(Path(output_text))
                if rdg_path is not None and signrho_path is not None:
                    self.log("Reopening PyVista viewer from existing NCI cube files.")
                    self.load_cubes_and_plot()
                else:
                    self.log("No loaded or existing NCI cube pair is available to reopen.")

        if not controls_open:
            self.show_viewer_controls()

        if self.is_plotter_alive():
            bring_pyvista_window_to_front(self.plotter, delay_s=0.05)

    def edit_template_dialog(self) -> None:
        win = tk.Toplevel(self.root)
        win.title("Edit Multiwfn command template")
        win.geometry(f"800x{screen_fraction_height(win)}")
        configure_builder_ui_style(win)

        frame = ttk.Frame(win, style="Panel.TFrame", padding=10)
        frame.pack(fill="both", expand=True)

        info = (
            "Insert the exact Multiwfn batch command sequence for generating NCI/RDG cube files.\n"
            "This is version-dependent, so the default template is intentionally not assumed to be correct.\n"
            "The command is run as: Multiwfn input.wfn < this_template.txt\n"
        )
        ttk.Label(frame, text=info, justify="left").pack(anchor="w", pady=(0, 8))

        text = tk.Text(frame, wrap="none", font=("Consolas", 10), relief="solid", bd=1)
        text.pack(fill="both", expand=True)
        text.insert("1.0", self.command_template.get())

        button_frame = ttk.Frame(frame)
        button_frame.pack(fill="x", pady=(8, 0))

        def save_and_close() -> None:
            self.command_template.set(text.get("1.0", "end-1c"))
            self.save_config()
            self.log("Multiwfn command template updated.")
            win.destroy()

        def reset_template() -> None:
            text.delete("1.0", "end")
            text.insert("1.0", DEFAULT_MULTIWFN_TEMPLATE)

        ttk.Button(button_frame, text="Save", command=save_and_close).pack(
            side="left", padx=(0, 6)
        )
        ttk.Button(button_frame, text="Reset default", command=reset_template).pack(
            side="left", padx=6
        )
        ttk.Button(button_frame, text="Cancel", command=win.destroy).pack(side="right")

    def on_close(self) -> None:
        self.save_config()
        try:
            if self.plotter is not None:
                self.plotter.close()
        except Exception:
            pass
        self.root.destroy()


def main() -> None:
    initial_wavefunction_path = sys.argv[1] if len(sys.argv) > 1 else None
    set_windows_app_id("NCI")
    root = tk.Tk()
    configure_tk_window_identity(root, "NCI")
    app = NCIPlotterApp(root, initial_wavefunction_path=initial_wavefunction_path)
    install_dev_reload_shortcut(root, Path(__file__), can_restart=lambda: not app.generation_lock.locked())
    root.protocol("WM_DELETE_WINDOW", app.on_close)
    root.mainloop()


if __name__ == "__main__":
    main()
