#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
nci_plotter.py

Standalone GUI utility for generating and visualizing NCI plots.

Required input:
    - .wfn
    - .wfx

Rejected input:
    - .out / .log, because ORCA output files do not contain the full
      wavefunction/electron-density information required for NCI/RDG analysis.

Required external program:
    - Multiwfn

How to run:
    py -3.12 nci_plotter.py

Main controls:
    - Select wavefunction file.
    - Select Multiwfn executable.
    - Generate NCI data through Multiwfn batch mode.
    - Display RDG isosurface colored by sign(lambda2)rho in PyVista.
    - Adjust RDG isovalue, opacity, color range, colormap, molecule visibility,
      bond visibility, scalar bar visibility, and background color.

Important scientific constraint:
    This script does NOT generate fake or approximate NCI plots.
    It only visualizes actual volumetric data generated by Multiwfn from the
    selected wavefunction file.
"""

from __future__ import annotations

import json
import os
import queue
import shutil
import subprocess
import sys
import threading
import time
import webbrowser
from dataclasses import dataclass
from pathlib import Path
from typing import Optional, Tuple

import numpy as np

try:
    import tkinter as tk
    from tkinter import filedialog, messagebox, ttk
except Exception as exc:
    raise RuntimeError("Tkinter is required but could not be imported.") from exc


CONFIG_FILE = Path.home() / ".nci_plotter_config.json"
TOOLS_ROOT = Path(__file__).resolve().parents[1]
APP_ROOT = TOOLS_ROOT.parent
NCI_ICON_PATH = TOOLS_ROOT / "images" / "tr_NCI_icon.png"
COPYRIGHT_NOTE = "(c) Yury Torubaev, 2026"
GITHUB_URL = "https://github.com/torubaev/crystengkit-orca-v1.0"
README_LINK_TEXT = "README section: NCI Plotter"
README_ANCHOR = "nci-plotter"


def wiki_url() -> str:
    return GITHUB_URL + f"#{README_ANCHOR}"


def open_readme_or_wiki() -> None:
    webbrowser.open(wiki_url(), new=2)
ABOUT_PURPOSE = (
    "Creates noncovalent-interaction surfaces from .wfn or .wfx files. It is useful for "
    "visualizing weak contacts, attractive regions, and repulsive regions in molecular "
    "associates, and it can open the NCI + QTAIM overlay viewer when matching topology "
    "files are available."
)
MAX_RECENT_FILES = 5
IMAGE_PRESETS = {
    "Viewer window": None,
    "Preview: 1600 x 1200 px": (1600, 1200),
    "Paper 300 dpi: 3000 x 2250 px": (3000, 2250),
    "Paper 600 dpi: 6000 x 4500 px": (6000, 4500),
    "Poster / high-res: 8000 x 6000 px": (8000, 6000),
}
DEFAULT_IMAGE_PRESET = "Paper 300 dpi: 3000 x 2250 px"

SUPPORTED_WAVEFUNCTION_EXTS = {".wfn", ".wfx"}
REJECTED_EXTS = {".out", ".log"}


def find_multiwfn() -> Optional[str]:
    candidates = [
        r"C:\Multiwfn_2026.2.2_bin_Win64\Multiwfn.exe",
        r"C:\Multiwfn\Multiwfn.exe",
        r"C:\Multiwfn_3.8_dev_bin_Win64\Multiwfn.exe",
    ]
    for candidate in candidates:
        if Path(candidate).exists():
            return candidate
    return shutil.which("Multiwfn") or shutil.which("Multiwfn.exe") or shutil.which("multiwfn")


def likely_multiwfn_search_roots() -> list[Path]:
    roots: list[Path] = []
    home = Path.home()

    def add(path: Path) -> None:
        try:
            if path.exists() and path.is_dir():
                roots.append(path)
        except OSError:
            pass

    for item in [
        Path.cwd(),
        Path(__file__).resolve().parents[1],
        home / "Desktop",
        home / "Downloads",
        home / "Documents",
        home / "Applications",
        home / "bin",
        home / ".local" / "bin",
    ]:
        add(item)

    if os.name == "nt":
        for env_name in ("ProgramFiles", "ProgramFiles(x86)", "LOCALAPPDATA"):
            env_value = os.environ.get(env_name)
            if env_value:
                env_path = Path(env_value)
                add(env_path)
                try:
                    for item in env_path.glob("*Multiwfn*"):
                        add(item)
                    for item in env_path.glob("*multiwfn*"):
                        add(item)
                except OSError:
                    pass
        add(Path("C:/"))
    else:
        for item in [Path("/"), Path("/opt"), Path("/usr/local"), Path("/usr/local/bin"), Path("/usr/bin")]:
            add(item)

    unique: list[Path] = []
    seen = set()
    for root in roots:
        try:
            key = str(root.resolve()).lower()
        except OSError:
            key = str(root).lower()
        if key not in seen:
            seen.add(key)
            unique.append(root)
    return unique


def find_multiwfn_deep(max_seconds: float = 18.0, max_visited: int = 70000, max_depth: int = 6) -> Optional[str]:
    quick = find_multiwfn()
    if quick:
        return quick

    target_names = {"multiwfn", "multiwfn.exe"}
    skip_dirs = {
        "$Recycle.Bin", ".git", ".hg", ".svn", "__pycache__", "node_modules",
        "System Volume Information", "Windows", "WinSxS", "Microsoft", "Packages", "Temp", "tmp",
    }
    started = time.monotonic()
    visited = 0

    def timed_out() -> bool:
        return (time.monotonic() - started) > max_seconds

    def scan(folder: Path, depth: int) -> Optional[str]:
        nonlocal visited
        if timed_out() or visited >= max_visited or depth > max_depth:
            return None
        try:
            with os.scandir(folder) as iterator:
                entries = list(iterator)
        except (OSError, PermissionError):
            return None
        for entry in entries:
            if timed_out() or visited >= max_visited:
                return None
            visited += 1
            try:
                if entry.is_file(follow_symlinks=False) and entry.name.lower() in target_names:
                    return str(Path(entry.path).resolve())
                if entry.is_dir(follow_symlinks=False) and entry.name not in skip_dirs:
                    found = scan(Path(entry.path), depth + 1)
                    if found:
                        return found
            except (OSError, PermissionError):
                continue
        return None

    for root in likely_multiwfn_search_roots():
        found = scan(root, 0)
        if found:
            return found
        if timed_out():
            break
    return None


def configure_builder_ui_style(widget: tk.Misc) -> None:
    style = ttk.Style(widget)
    try:
        style.theme_use("clam")
    except tk.TclError:
        pass

    try:
        widget.configure(background="#f4f6f9")
    except tk.TclError:
        pass

    style.configure("TFrame", background="#f4f6f9")
    style.configure("Panel.TFrame", background="#f4f6f9")
    style.configure("Header.TFrame", background="#1e3a5f")
    style.configure("HeaderTitle.TLabel", background="#1e3a5f", foreground="#f8fafc", font=("Segoe UI", 15, "bold"))
    style.configure("HeaderSub.TLabel", background="#1e3a5f", foreground="#d7e1ee", font=("Segoe UI", 10, "bold"))
    style.configure("HeaderAction.TLabel", background="#1e3a5f", foreground="#d7e1ee", font=("Segoe UI", 9, "bold"))
    style.configure("HeaderLink.TLabel", background="#1e3a5f", foreground="#ffffff", font=("Segoe UI", 11, "bold"))
    style.configure("TLabelframe", background="#f8fafc", bordercolor="#d8dee8", relief="solid", padding=8)
    style.configure("TLabelframe.Label", background="#f8fafc", foreground="#172033", font=("Segoe UI", 10, "bold"))
    style.configure("TButton", padding=(9, 5), font=("Segoe UI", 9))
    style.configure("Primary.TButton", padding=(14, 8), font=("Segoe UI", 10, "bold"))
    style.configure(
        "HeaderCTA.TButton",
        background="#2f80c8",
        foreground="#ffffff",
        bordercolor="#61a5e8",
        lightcolor="#2f80c8",
        darkcolor="#2f80c8",
        focusthickness=0,
        padding=(14, 7),
        relief="flat",
        font=("Segoe UI", 9, "bold"),
    )
    style.map(
        "HeaderCTA.TButton",
        background=[("active", "#3b94df"), ("pressed", "#1f68a8")],
        foreground=[("active", "#ffffff"), ("pressed", "#ffffff")],
        bordercolor=[("active", "#8ac4f4"), ("pressed", "#1f68a8")],
    )
    style.configure("Info.TButton", padding=(3, 1), font=("Segoe UI", 9, "bold"))
    style.configure("TCheckbutton", background="#f8fafc", padding=(1, 2), font=("Segoe UI", 9))
    style.configure("TLabel", background="#f8fafc", foreground="#263348", padding=(1, 1), font=("Segoe UI", 9))
    style.configure("Muted.TLabel", background="#f4f6f9", foreground="#53627a", font=("Segoe UI", 9))


def keep_entry_end_visible(entry: tk.Entry, variable: Optional[tk.Variable] = None) -> tk.Entry:
    def show_end(*_args) -> None:
        try:
            entry.icursor("end")
            entry.xview_moveto(1.0)
        except tk.TclError:
            pass

    entry.bind("<Configure>", lambda _event: entry.after_idle(show_end), add="+")
    entry.bind("<FocusOut>", lambda _event: entry.after_idle(show_end), add="+")
    if variable is not None:
        variable.trace_add("write", lambda *_args: entry.after_idle(show_end))
    entry.after_idle(show_end)
    return entry


def bind_mousewheel_to_canvas(canvas: tk.Canvas, *_hover_widgets: tk.Misc) -> None:
    def _pointer_is_over_canvas() -> bool:
        try:
            x = canvas.winfo_pointerx()
            y = canvas.winfo_pointery()
            left = canvas.winfo_rootx()
            top = canvas.winfo_rooty()
            return left <= x < left + canvas.winfo_width() and top <= y < top + canvas.winfo_height()
        except tk.TclError:
            return False

    def _can_scroll() -> bool:
        try:
            first, last = canvas.yview()
            return first > 0.0 or last < 1.0
        except tk.TclError:
            return False

    def _wheel_units(event) -> int:
        if getattr(event, "num", None) == 4:
            return -5
        if getattr(event, "num", None) == 5:
            return 5
        delta = getattr(event, "delta", 0)
        if delta == 0:
            return 0
        if abs(delta) >= 120:
            return int(-delta / 120) * 5
        return -5 if delta > 0 else 5

    def _on_mousewheel(event):
        if not _pointer_is_over_canvas() or not _can_scroll():
            return None
        units = _wheel_units(event)
        if units:
            canvas.yview_scroll(units, "units")
        return "break"

    canvas.bind_all("<MouseWheel>", _on_mousewheel, add="+")
    canvas.bind_all("<Button-4>", _on_mousewheel, add="+")
    canvas.bind_all("<Button-5>", _on_mousewheel, add="+")


def configure_pyvista_defaults(pv_module, plotter, background="white", parallel_projection=True, antialiasing=None, extent=1.0):
    """Apply conservative PyVista defaults that work on limited OpenGL contexts."""
    try:
        pv_module.global_theme.multi_samples = 0
    except Exception:
        pass

    try:
        pv_module.global_theme.smooth_shading = False
    except Exception:
        pass

    try:
        plotter.set_background(background)
    except Exception:
        try:
            plotter.set_background("white")
        except Exception:
            pass

    if antialiasing:
        try:
            plotter.enable_anti_aliasing(antialiasing)
        except Exception:
            pass

    try:
        plotter.enable_depth_peeling(number_of_peels=8, occlusion_ratio=0.0)
    except Exception:
        pass

    try:
        plotter.renderer.SetTwoSidedLighting(True)
    except Exception:
        pass

    if parallel_projection:
        try:
            plotter.enable_parallel_projection()
        except Exception:
            pass

    try:
        plotter.remove_all_lights()
    except Exception:
        pass

    try:
        extent = max(float(extent), 1.0)
    except Exception:
        extent = 1.0

    light_specs = [
        ("headlight", None, 0.95),
        ("camera light", None, 0.45),
        ("scene light", (3.0 * extent, -4.0 * extent, 5.0 * extent), 0.35),
        ("scene light", (-3.0 * extent, 3.0 * extent, 4.0 * extent), 0.25),
    ]

    for light_type, position, intensity in light_specs:
        try:
            if light_type in {"headlight", "camera light"}:
                light = pv_module.Light(light_type=light_type)
            else:
                light = pv_module.Light(
                    position=position,
                    focal_point=(0.0, 0.0, 0.0),
                    color="white",
                    light_type="scene light",
                )
            light.intensity = intensity
            plotter.add_light(light)
        except Exception:
            pass


def should_use_transparent_png(path: str, background: str) -> bool:
    return str(path).lower().endswith(".png") and str(background or "").strip().lower() == "white"


def save_pyvista_screenshot(plotter, path: str, background: str, **kwargs):
    if should_use_transparent_png(path, background):
        try:
            return plotter.screenshot(path, transparent_background=True, **kwargs)
        except TypeError:
            pass
    return plotter.screenshot(path, **kwargs)


def bring_pyvista_window_to_front(plotter, delay_s: float = 0.25) -> None:
    def worker() -> None:
        try:
            if delay_s > 0:
                time.sleep(delay_s)
            render_window = getattr(plotter, "ren_win", None) or getattr(plotter, "render_window", None)
            if render_window is None:
                return
            handle = None
            for attr in ("GetGenericWindowId", "GetWindowId"):
                getter = getattr(render_window, attr, None)
                if callable(getter):
                    handle = getter()
                    if handle:
                        break
            if not handle or os.name != "nt":
                return
            hwnd = int(handle)
            import ctypes

            user32 = ctypes.windll.user32
            flags = 0x0001 | 0x0002 | 0x0040
            user32.ShowWindow(hwnd, 5)
            user32.SetWindowPos(hwnd, -1, 0, 0, 0, 0, flags)
            user32.SetWindowPos(hwnd, -2, 0, 0, 0, 0, flags)
            user32.SetForegroundWindow(hwnd)
        except Exception:
            pass

    threading.Thread(target=worker, daemon=True).start()

LEGACY_SAFE_MULTIWFN_TEMPLATE = """\
# Multiwfn batch-command template.
#
# IMPORTANT:
# Multiwfn menu numbers can differ between versions.
# Replace this template with the exact command sequence that generates:
#   1) RDG cube
#   2) sign(lambda2)rho cube
#
# The command is run internally as:
#   Multiwfn input.wfn < multiwfn_nci_input.txt
#
# The default template only exits Multiwfn. It is intentionally safe.
# It will NOT generate NCI data until you replace it with a validated
# command sequence for your installed Multiwfn version.
q
"""

DEFAULT_MULTIWFN_TEMPLATE = """\
# Multiwfn 2026.x NCI/RDG cube export template.
#
# Expected Multiwfn route:
#   20  = Visual study of weak interaction
#   1   = NCI analysis
#   3   = High-quality grid covering the whole system
#   3   = Output cube files to func1.cub and func2.cub
#   0   = Return / exit from post-processing menu
#   q   = Quit Multiwfn
#
# Multiwfn convention for this NCI export:
#   func1.cub = sign(lambda2)rho
#   func2.cub = RDG
#
# If this sequence does not match your exact Multiwfn build, edit it from:
#   Edit Multiwfn command template
20
1
3
3
0
q
"""


COVALENT_RADII = {
    1: 0.31,
    2: 0.28,
    3: 1.28,
    4: 0.96,
    5: 0.84,
    6: 0.76,
    7: 0.71,
    8: 0.66,
    9: 0.57,
    10: 0.58,
    11: 1.66,
    12: 1.41,
    13: 1.21,
    14: 1.11,
    15: 1.07,
    16: 1.05,
    17: 1.02,
    18: 1.06,
    19: 2.03,
    20: 1.76,
    21: 1.70,
    22: 1.60,
    23: 1.53,
    24: 1.39,
    25: 1.39,
    26: 1.32,
    27: 1.26,
    28: 1.24,
    29: 1.32,
    30: 1.22,
    31: 1.22,
    32: 1.20,
    33: 1.19,
    34: 1.20,
    35: 1.20,
    36: 1.16,
    37: 2.20,
    38: 1.95,
    39: 1.90,
    40: 1.75,
    41: 1.64,
    42: 1.54,
    43: 1.47,
    44: 1.46,
    45: 1.42,
    46: 1.39,
    47: 1.45,
    48: 1.44,
    49: 1.42,
    50: 1.39,
    51: 1.39,
    52: 1.38,
    53: 1.39,
    54: 1.40,
    55: 2.44,
    56: 2.15,
    57: 2.07,
    58: 2.04,
    59: 2.03,
    60: 2.01,
    61: 1.99,
    62: 1.98,
    63: 1.98,
    64: 1.96,
    65: 1.94,
    66: 1.92,
    67: 1.92,
    68: 1.89,
    69: 1.90,
    70: 1.87,
    71: 1.87,
    72: 1.75,
    73: 1.70,
    74: 1.62,
    75: 1.51,
    76: 1.44,
    77: 1.41,
    78: 1.36,
    79: 1.36,
    80: 1.32,
    81: 1.45,
    82: 1.46,
    83: 1.48,
    84: 1.40,
    85: 1.50,
    86: 1.50,
    87: 2.60,
    88: 2.21,
    89: 2.15,
    90: 2.06,
    91: 2.00,
    92: 1.96,
    93: 1.90,
    94: 1.87,
    95: 1.80,
    96: 1.69,
}


ATOM_COLORS = {
    1: "#F2F2F2",
    5: "#FFB5B5",
    6: "#5A5A5A",
    7: "#3050F8",
    8: "#FF0D0D",
    9: "#90E050",
    14: "#F0C8A0",
    15: "#FF8000",
    16: "#FFFF30",
    17: "#1FF01F",
    26: "#E06633",
    27: "#F090A0",
    28: "#50D050",
    29: "#C88033",
    30: "#7D80B0",
    35: "#A62929",
    44: "#248F8F",
    45: "#0A7D8C",
    46: "#006985",
    47: "#C0C0C0",
    53: "#940094",
    77: "#175487",
    78: "#D0D0E0",
    79: "#FFD123",
}

NCI_SCALAR_NAME = "sign(lambda2)rho"
NCI_SCALAR_BAR_TITLE = "sign(lambda2)rho\n\n\n"


def contrast_text_color(background: str) -> str:
    colors = {
        "white": "black",
        "lightgray": "black",
        "gray": "white",
        "black": "white",
    }
    bg = str(background or "").strip().lower()
    if bg in colors:
        return colors[bg]
    if bg.startswith("#") and len(bg) in {4, 7}:
        try:
            if len(bg) == 4:
                r = int(bg[1] * 2, 16)
                g = int(bg[2] * 2, 16)
                b = int(bg[3] * 2, 16)
            else:
                r = int(bg[1:3], 16)
                g = int(bg[3:5], 16)
                b = int(bg[5:7], 16)
            luminance = (0.2126 * r + 0.7152 * g + 0.0722 * b) / 255.0
            return "black" if luminance > 0.55 else "white"
        except Exception:
            pass
    return "black"


def molecule_material_parameters() -> dict[str, object]:
    return {
        "lighting": True,
        "smooth_shading": True,
        "ambient": 0.50,
        "diffuse": 0.62,
        "specular": 0.18,
        "specular_power": 20,
    }


def add_mesh_safe(plotter, mesh, **kwargs):
    try:
        plotter.add_mesh(mesh, **kwargs)
    except TypeError:
        safe_kwargs = dict(kwargs)
        safe_kwargs.pop("pbr", None)
        safe_kwargs.pop("metallic", None)
        safe_kwargs.pop("roughness", None)
        plotter.add_mesh(mesh, **safe_kwargs)


def set_scalar_bar_text_color(plotter, text_color: str, title: str | None = None) -> None:
    try:
        scalar_bars = getattr(plotter, "scalar_bars", {})
        scalar_bar = scalar_bars.get(title) if title else None
        if scalar_bar is None:
            bars = list(scalar_bars.values())
            if not bars:
                return
            scalar_bar = bars[0]
        import pyvista as pv
        rgb = pv.Color(text_color).float_rgb
        title_prop = scalar_bar.GetTitleTextProperty()
        label_prop = scalar_bar.GetLabelTextProperty()
        title_prop.SetColor(*rgb)
        label_prop.SetColor(*rgb)
        title_prop.BoldOn()
        label_prop.BoldOn()
        title_prop.SetFontSize(16)
        label_prop.SetFontSize(12)
    except Exception:
        pass


def hex_to_rgb01(color: str) -> tuple[float, float, float]:
    color = color.lstrip("#")
    return tuple(int(color[i:i + 2], 16) / 255.0 for i in (0, 2, 4))


def configure_molecule_renderer_lights(pv_module, renderer, extent: float) -> None:
    try:
        renderer.RemoveAllLights()
    except Exception:
        pass

    try:
        extent = max(float(extent), 1.0)
    except Exception:
        extent = 1.0

    light_specs = [
        ("headlight", None, 0.95),
        ("camera light", None, 0.45),
        ("scene light", (3.0 * extent, -4.0 * extent, 5.0 * extent), 0.35),
        ("scene light", (-3.0 * extent, 3.0 * extent, 4.0 * extent), 0.25),
    ]

    for light_type, position, intensity in light_specs:
        try:
            if light_type in {"headlight", "camera light"}:
                light = pv_module.Light(light_type=light_type)
            else:
                light = pv_module.Light(
                    position=position,
                    focal_point=(0.0, 0.0, 0.0),
                    color="white",
                    light_type="scene light",
                )
            light.intensity = intensity
            renderer.AddLight(light)
        except Exception:
            pass


@dataclass
class CubeData:
    path: Path
    origin: np.ndarray
    axes: np.ndarray
    shape: tuple[int, int, int]
    atom_numbers: list[int]
    atom_coords: np.ndarray
    values: np.ndarray


class CubeParseError(Exception):
    """Raised when a cube file cannot be parsed safely."""


class CubeParser:
    BOHR_TO_ANG = 0.529177210903

    @staticmethod
    def parse(path: Path) -> CubeData:
        if not path.exists():
            raise CubeParseError(f"Cube file not found: {path}")

        try:
            lines = path.read_text(encoding="utf-8", errors="replace").splitlines()
        except Exception as exc:
            raise CubeParseError(f"Could not read cube file: {path}") from exc

        if len(lines) < 6:
            raise CubeParseError(f"Malformed cube file: too few lines: {path}")

        try:
            atom_line = lines[2].split()
            natoms_raw = int(float(atom_line[0]))
            natoms = abs(natoms_raw)

            origin = np.array(
                [float(atom_line[1]), float(atom_line[2]), float(atom_line[3])],
                dtype=float,
            )

            axes = []
            shape = []

            for i in range(3):
                parts = lines[3 + i].split()
                n = int(float(parts[0]))
                shape.append(abs(n))
                axes.append([float(parts[1]), float(parts[2]), float(parts[3])])

            axes_arr = np.array(axes, dtype=float)
            shape_tuple = (shape[0], shape[1], shape[2])

            atom_numbers: list[int] = []
            atom_coords_list = []

            for i in range(natoms):
                parts = lines[6 + i].split()
                atom_numbers.append(int(float(parts[0])))
                atom_coords_list.append(
                    [float(parts[2]), float(parts[3]), float(parts[4])]
                )

            atom_coords = np.array(atom_coords_list, dtype=float)

            data_start = 6 + natoms
            raw_values = []

            for line in lines[data_start:]:
                for token in line.split():
                    raw_values.append(float(token.replace("D", "E").replace("d", "e")))

            expected = shape_tuple[0] * shape_tuple[1] * shape_tuple[2]

            if len(raw_values) < expected:
                raise CubeParseError(
                    f"Malformed cube file: expected {expected} grid values, "
                    f"found {len(raw_values)}: {path}"
                )

            values = np.array(raw_values[:expected], dtype=float).reshape(
                shape_tuple, order="C"
            )

            if natoms_raw > 0:
                origin = origin * CubeParser.BOHR_TO_ANG
                axes_arr = axes_arr * CubeParser.BOHR_TO_ANG
                atom_coords = atom_coords * CubeParser.BOHR_TO_ANG

            return CubeData(
                path=path,
                origin=origin,
                axes=axes_arr,
                shape=shape_tuple,
                atom_numbers=atom_numbers,
                atom_coords=atom_coords,
                values=values,
            )

        except CubeParseError:
            raise
        except Exception as exc:
            raise CubeParseError(f"Malformed cube file: {path}") from exc


def screen_fraction_height(widget: tk.Misc, fraction: float = 0.80, fallback: int = 760) -> int:
    try:
        return max(1, int(widget.winfo_screenheight() * fraction))
    except Exception:
        return fallback


def load_header_icon(path: Path, max_size: int = 56) -> Optional[tk.PhotoImage]:
    if not path.is_file():
        return None
    img = tk.PhotoImage(file=str(path))
    factor = max(1, int(max(img.width() / max_size, img.height() / max_size) + 0.999))
    if factor > 1:
        img = img.subsample(factor, factor)
    return img


def open_about_dialog(parent: tk.Misc, title: str, icon_path: Path, purpose: str) -> None:
    win = tk.Toplevel(parent)
    win.title("About")
    win.transient(parent)
    win.columnconfigure(0, weight=1)

    box = ttk.Frame(win, padding=14)
    box.grid(row=0, column=0, sticky="nsew")
    box.columnconfigure(1, weight=1)

    icon = load_header_icon(icon_path, max_size=144)
    if icon is not None:
        win.about_icon = icon
        ttk.Label(box, image=icon).grid(row=0, column=0, rowspan=7, sticky="n", padx=(0, 14))

    ttk.Label(box, text=title, font=("Segoe UI", 12, "bold")).grid(row=0, column=1, sticky="w")
    ttk.Label(box, text=purpose, justify="left", wraplength=420).grid(row=1, column=1, sticky="w", pady=(8, 0))
    ttk.Label(box, text="GitHub:", justify="left").grid(row=2, column=1, sticky="w", pady=(10, 0))
    github_link = ttk.Label(box, text=GITHUB_URL, foreground="#1d4ed8", cursor="hand2", justify="left")
    github_link.grid(row=3, column=1, sticky="w", pady=(2, 0))
    github_link.bind("<Button-1>", lambda _event: webbrowser.open(GITHUB_URL))
    ttk.Label(box, text="README:", justify="left").grid(row=4, column=1, sticky="w", pady=(10, 0))
    wiki_link = ttk.Label(box, text=README_LINK_TEXT, foreground="#1d4ed8", cursor="hand2", justify="left")
    wiki_link.grid(row=5, column=1, sticky="w", pady=(2, 0))
    wiki_link.bind("<Button-1>", lambda _event: open_readme_or_wiki())
    ttk.Label(box, text=COPYRIGHT_NOTE, justify="left").grid(row=6, column=1, sticky="w", pady=(10, 0))

    ttk.Button(box, text="Close", command=win.destroy).grid(row=7, column=0, columnspan=2, sticky="e", pady=(14, 0))
    win.geometry("570x340")
    win.minsize(470, 290)
    win.grab_set()


class NCIPlotterApp:
    def __init__(self, root: tk.Tk, initial_wavefunction_path: Optional[str] = None):
        self.root = root
        self.root.title("NCI Plotter")
        self.window_height = screen_fraction_height(self.root)
        self.root.geometry(f"980x{self.window_height}")
        configure_builder_ui_style(self.root)

        self.config = self.load_config()

        self.wavefunction_path = tk.StringVar(value="")
        self.multiwfn_path = tk.StringVar(value=self.config.get("multiwfn_path", ""))
        self.output_dir = tk.StringVar(value="")

        self.rdg_isovalue = tk.DoubleVar(value=0.50)
        self.opacity = tk.DoubleVar(value=0.75)
        self.color_min = tk.StringVar(value="-0.05")
        self.color_max = tk.StringVar(value="0.05")
        self.colormap = tk.StringVar(value="rainbow")
        self.show_molecule = tk.BooleanVar(value=True)
        self.show_bonds = tk.BooleanVar(value=True)
        self.show_scalar_bar = tk.BooleanVar(value=True)
        self.background = tk.StringVar(value="white")
        self.image_resolution = tk.StringVar(value=self.config.get("image_resolution", DEFAULT_IMAGE_PRESET))

        self.command_template = tk.StringVar(
            value=self.config.get("multiwfn_template", DEFAULT_MULTIWFN_TEMPLATE)
        )

        self.log_queue: queue.Queue[str] = queue.Queue()

        self.rdg_cube: Optional[CubeData] = None
        self.signrho_cube: Optional[CubeData] = None
        self.rdg_cube_path: Optional[Path] = None
        self.signrho_cube_path: Optional[Path] = None
        self.auto_start_requested = bool(initial_wavefunction_path)
        self.generation_lock = threading.Lock()
        self.generate_button: Optional[ttk.Button] = None

        self.plotter = None
        self.header_icon: Optional[tk.PhotoImage] = None

        self.build_gui()
        if initial_wavefunction_path:
            self.set_wavefunction_path(initial_wavefunction_path)
        self.root.after(150, self.process_log_queue)
        self.start_multiwfn_locator()
        if self.auto_start_requested:
            self.root.after(900, self.auto_start_from_initial_wavefunction)

    def load_config(self) -> dict:
        if CONFIG_FILE.exists():
            try:
                config = json.loads(CONFIG_FILE.read_text(encoding="utf-8"))
            except Exception:
                return {}
            template = str(config.get("multiwfn_template", "")).strip()
            if template == "q" or template == LEGACY_SAFE_MULTIWFN_TEMPLATE.strip():
                config["multiwfn_template"] = DEFAULT_MULTIWFN_TEMPLATE
            return config
        return {}

    def save_config(self) -> None:
        self.config["multiwfn_path"] = self.multiwfn_path.get()
        self.config["multiwfn_template"] = self.command_template.get()
        self.config["image_resolution"] = self.image_resolution.get()
        try:
            CONFIG_FILE.write_text(json.dumps(self.config, indent=2), encoding="utf-8")
        except Exception as exc:
            self.log(f"WARNING: Could not save config: {exc}")

    def selected_image_size(self) -> Optional[Tuple[int, int]]:
        return IMAGE_PRESETS.get(self.image_resolution.get(), IMAGE_PRESETS[DEFAULT_IMAGE_PRESET])

    def recent_wavefunction_files(self) -> list[str]:
        values = self.config.get("recent_wavefunction_files", [])
        if isinstance(values, list):
            return [str(item) for item in values if str(item).strip()][:MAX_RECENT_FILES]
        return []

    def remember_wavefunction_file(self, path: Path) -> None:
        clean = str(path)
        recent = [clean] + [
            item for item in self.recent_wavefunction_files()
            if os.path.normcase(item) != os.path.normcase(clean)
        ]
        self.config["recent_wavefunction_files"] = recent[:MAX_RECENT_FILES]
        try:
            self.wavefunction_combo.configure(values=self.config["recent_wavefunction_files"])
        except Exception:
            pass
        self.save_config()

    def start_multiwfn_locator(self) -> None:
        if self.multiwfn_path.get().strip():
            return

        def worker() -> None:
            found = find_multiwfn_deep()
            self.root.after(0, lambda: self.finish_multiwfn_locator(found))

        threading.Thread(target=worker, daemon=True).start()

    def finish_multiwfn_locator(self, found: Optional[str]) -> None:
        if found and not self.multiwfn_path.get().strip():
            self.multiwfn_path.set(found)
            self.save_config()
            if self.auto_start_requested:
                self.root.after(250, self.auto_start_from_initial_wavefunction)

    def auto_start_from_initial_wavefunction(self) -> None:
        if not self.auto_start_requested:
            return
        if not self.wavefunction_path.get().strip():
            return
        if not self.multiwfn_path.get().strip() and not find_multiwfn():
            self.log("Automatic NCI plotting is waiting for Multiwfn detection.")
            return
        self.auto_start_requested = False
        self.log("Automatic NCI workflow started from the selected wavefunction file.")
        self.start_generate_nci(auto_open=True)

    def build_gui(self) -> None:
        header = ttk.Frame(self.root, style="Header.TFrame", padding=(14, 10))
        header.pack(fill="x")
        self.header_icon = load_header_icon(NCI_ICON_PATH)
        if self.header_icon is not None:
            tk.Label(header, image=self.header_icon, bg="#1e3a5f", bd=0, highlightthickness=0).grid(row=0, column=0, rowspan=2, sticky="w", padx=(0, 10))
        ttk.Label(header, text="NCI Plotter", style="HeaderTitle.TLabel").grid(row=0, column=1, sticky="w")
        ttk.Label(
            header,
            text="Non-covalent interaction surfaces",
            style="HeaderSub.TLabel",
        ).grid(row=1, column=1, sticky="w")
        header.columnconfigure(2, weight=1)
        header_actions = ttk.Frame(header, style="Header.TFrame")
        header_actions.grid(row=0, column=3, rowspan=2, sticky="e")
        about_link = ttk.Label(header_actions, text="About", style="HeaderLink.TLabel", cursor="hand2")
        about_link.pack(side="right", padx=(12, 0))
        about_link.bind(
            "<Button-1>",
            lambda _event: open_about_dialog(self.root, "NCI Plotter", NCI_ICON_PATH, ABOUT_PURPOSE),
        )
        ttk.Button(
            header_actions,
            text="NCI + QTAIM overlay",
            command=self.open_nci_qtaim_overlay,
            style="HeaderCTA.TButton",
        ).pack(side="right")

        main_host = ttk.Frame(self.root, style="Panel.TFrame")
        main_host.pack(fill="both", expand=True)
        main_host.rowconfigure(0, weight=1)
        main_host.columnconfigure(0, weight=1)
        main_canvas = tk.Canvas(main_host, highlightthickness=0, borderwidth=0, bg="#f4f6f9")
        main_scroll = ttk.Scrollbar(main_host, orient="vertical", command=main_canvas.yview)
        main_canvas.configure(yscrollcommand=main_scroll.set)
        main_canvas.grid(row=0, column=0, sticky="nsew")
        main_scroll.grid(row=0, column=1, sticky="ns")

        main = ttk.Frame(main_canvas, style="Panel.TFrame", padding=10)
        main_window = main_canvas.create_window((0, 0), window=main, anchor="nw")
        main.bind("<Configure>", lambda _e: main_canvas.configure(scrollregion=main_canvas.bbox("all")))
        main_canvas.bind("<Configure>", lambda e: main_canvas.itemconfigure(main_window, width=e.width))
        bind_mousewheel_to_canvas(main_canvas, main)

        footer = ttk.Frame(self.root, style="Panel.TFrame", padding=(12, 6))
        footer.pack(side="bottom", fill="x")
        ttk.Label(footer, text=COPYRIGHT_NOTE, style="Muted.TLabel").pack(anchor="w")

        input_frame = ttk.LabelFrame(main, text="Input", padding=8)
        input_frame.pack(fill="x", pady=(0, 8))

        ttk.Label(input_frame, text="Wavefunction file:").grid(row=0, column=0, sticky="w")
        self.wavefunction_combo = ttk.Combobox(input_frame, textvariable=self.wavefunction_path, values=self.recent_wavefunction_files())
        keep_entry_end_visible(self.wavefunction_combo, self.wavefunction_path)
        self.wavefunction_combo.grid(row=0, column=1, sticky="ew", padx=5)
        self.wavefunction_combo.bind("<<ComboboxSelected>>", lambda _e: self.set_wavefunction_path(self.wavefunction_path.get().strip()))
        ttk.Button(input_frame, text="Browse", command=self.browse_wavefunction).grid(
            row=0, column=2, padx=5
        )

        ttk.Label(input_frame, text="Output folder:").grid(
            row=1, column=0, sticky="w", pady=(6, 0)
        )
        output_entry = ttk.Entry(input_frame, textvariable=self.output_dir, state="readonly")
        keep_entry_end_visible(output_entry, self.output_dir)
        output_entry.grid(row=1, column=1, sticky="ew", padx=5, pady=(6, 0))

        input_frame.columnconfigure(1, weight=1)

        gen_frame = ttk.LabelFrame(main, text="NCI data generation", padding=8)
        gen_frame.pack(fill="x", pady=(0, 8))

        self.generate_button = ttk.Button(
            gen_frame,
            text="Generate NCI data",
            command=self.start_generate_nci,
            style="Primary.TButton",
        )
        self.generate_button.pack(side="left", padx=(0, 6))

        ttk.Button(
            gen_frame,
            text="Edit Multiwfn command template",
            command=self.edit_template_dialog,
        ).pack(side="left", padx=6)

        control_frame = ttk.LabelFrame(main, text="Visualization controls", padding=8)
        control_frame.pack(fill="x", pady=(0, 8))

        ttk.Label(control_frame, text="RDG isovalue").grid(row=0, column=0, sticky="w")
        ttk.Scale(
            control_frame,
            from_=0.1,
            to=1.5,
            variable=self.rdg_isovalue,
            orient="horizontal",
        ).grid(row=0, column=1, sticky="ew", padx=5)

        ttk.Entry(control_frame, textvariable=self.rdg_isovalue, width=10).grid(
            row=0, column=2, padx=5
        )

        ttk.Label(control_frame, text="Opacity").grid(
            row=1, column=0, sticky="w", pady=(6, 0)
        )
        ttk.Scale(
            control_frame,
            from_=0.05,
            to=1.0,
            variable=self.opacity,
            orient="horizontal",
        ).grid(row=1, column=1, sticky="ew", padx=5, pady=(6, 0))

        ttk.Entry(control_frame, textvariable=self.opacity, width=10).grid(
            row=1, column=2, padx=5, pady=(6, 0)
        )

        ttk.Label(control_frame, text="Color min").grid(
            row=2, column=0, sticky="w", pady=(6, 0)
        )
        ttk.Entry(control_frame, textvariable=self.color_min, width=12).grid(
            row=2, column=1, sticky="w", padx=5, pady=(6, 0)
        )

        ttk.Label(control_frame, text="Color max").grid(
            row=2, column=2, sticky="w", pady=(6, 0)
        )
        ttk.Entry(control_frame, textvariable=self.color_max, width=12).grid(
            row=2, column=3, sticky="w", padx=5, pady=(6, 0)
        )

        ttk.Label(control_frame, text="Colormap").grid(
            row=3, column=0, sticky="w", pady=(6, 0)
        )
        ttk.Combobox(
            control_frame,
            textvariable=self.colormap,
            values=["bwr", "seismic", "coolwarm", "rainbow", "jet", "viridis", "plasma"],
            width=14,
            state="readonly",
        ).grid(row=3, column=1, sticky="w", padx=5, pady=(6, 0))

        ttk.Label(control_frame, text="Background").grid(
            row=3, column=2, sticky="w", pady=(6, 0)
        )
        ttk.Combobox(
            control_frame,
            textvariable=self.background,
            values=["white", "black", "gray", "lightgray"],
            width=14,
            state="readonly",
        ).grid(row=3, column=3, sticky="w", padx=5, pady=(6, 0))

        ttk.Checkbutton(
            control_frame, text="Show molecule", variable=self.show_molecule
        ).grid(row=4, column=0, sticky="w", pady=(8, 0))

        ttk.Checkbutton(
            control_frame, text="Show bonds", variable=self.show_bonds
        ).grid(row=4, column=1, sticky="w", pady=(8, 0))

        ttk.Checkbutton(
            control_frame, text="Show scalar bar", variable=self.show_scalar_bar
        ).grid(row=4, column=2, sticky="w", pady=(8, 0))

        ttk.Label(control_frame, text="Image size").grid(
            row=5, column=0, sticky="w", pady=(8, 0)
        )
        ttk.Combobox(
            control_frame,
            textvariable=self.image_resolution,
            values=list(IMAGE_PRESETS.keys()),
            width=28,
            state="readonly",
        ).grid(row=5, column=1, columnspan=3, sticky="w", padx=5, pady=(8, 0))

        button_row = ttk.Frame(control_frame)
        button_row.grid(row=6, column=0, columnspan=4, sticky="w", pady=(10, 0))

        ttk.Button(button_row, text="Update plot", command=self.update_plot).pack(
            side="left", padx=(0, 6)
        )
        ttk.Button(button_row, text="Reset view", command=self.reset_view).pack(
            side="left", padx=6
        )
        ttk.Button(button_row, text="Save image", command=self.save_image).pack(
            side="left", padx=6
        )

        control_frame.columnconfigure(1, weight=1)

        log_frame = ttk.LabelFrame(main, text="Status / log", padding=8)
        log_frame.pack(fill="both", expand=True)

        self.log_text = tk.Text(log_frame, height=16, wrap="word", font=("Consolas", 10), relief="solid", bd=1)
        self.log_text.pack(side="left", fill="both", expand=True)

        scrollbar = ttk.Scrollbar(log_frame, orient="vertical", command=self.log_text.yview)
        scrollbar.pack(side="right", fill="y")
        self.log_text.configure(yscrollcommand=scrollbar.set)

        self.log("NCI Plotter started.")
        self.log("Select a .wfn or .wfx file.")
        self.log("The script will call Multiwfn to generate the real RDG and sign(lambda2)rho cube files automatically.")

    def log(self, text: str) -> None:
        timestamp = time.strftime("%H:%M:%S")
        self.log_queue.put(f"[{timestamp}] {text}\n")

    def process_log_queue(self) -> None:
        while True:
            try:
                msg = self.log_queue.get_nowait()
            except queue.Empty:
                break
            self.log_text.insert("end", msg)
            self.log_text.see("end")
        self.root.after(150, self.process_log_queue)

    def browse_wavefunction(self) -> None:
        path = filedialog.askopenfilename(
            title="Select wavefunction file",
            filetypes=[
                ("Wavefunction files", "*.wfn *.wfx"),
                ("Rejected ORCA output", "*.out *.log"),
                ("All files", "*.*"),
            ],
        )
        if not path:
            return

        self.set_wavefunction_path(path)
        self.root.after(100, lambda: self.start_generate_nci(auto_open=True))

    def set_wavefunction_path(self, path: str) -> None:
        p = Path(path)
        ext = p.suffix.lower()

        if ext in REJECTED_EXTS:
            messagebox.showerror(
                "Unsupported input",
                "ORCA .out/.log files are not valid NCI inputs.\n\n"
                "NCI analysis requires wavefunction/electron-density information.\n"
                "Please use .wfn or .wfx generated from ORCA, for example using orca_2aim.",
            )
            return

        if ext not in SUPPORTED_WAVEFUNCTION_EXTS:
            messagebox.showerror(
                "Unsupported input",
                f"Unsupported file type: {ext}\n\nUse .wfn or .wfx.",
            )
            return

        self.wavefunction_path.set(str(p))
        self.remember_wavefunction_file(p)
        outdir = p.with_suffix("")
        outdir = outdir.parent / f"{outdir.name}_NCI"
        self.output_dir.set(str(outdir))
        self.log(f"Selected wavefunction file: {p}")

    def prompt_for_multiwfn(self) -> Optional[str]:
        path = filedialog.askopenfilename(
            title="Select Multiwfn executable",
            filetypes=[
                ("Executable files", "*.exe *"),
                ("All files", "*.*"),
            ],
            parent=self.root,
        )
        if path:
            self.multiwfn_path.set(path)
            self.save_config()
            self.log(f"Selected Multiwfn executable: {path}")
            return path
        return None

    def ensure_multiwfn_available(self) -> Path:
        raw = self.multiwfn_path.get().strip()
        if raw:
            candidate = Path(raw)
            if candidate.exists():
                return candidate
            found = shutil.which(raw)
            if found:
                self.multiwfn_path.set(found)
                self.save_config()
                return Path(found)

        messagebox.showwarning(
            "Multiwfn not found",
            "Multiwfn was not found automatically. Please select the Multiwfn executable.",
            parent=self.root,
        )
        selected = self.prompt_for_multiwfn()
        if selected:
            candidate = Path(selected)
            if candidate.exists():
                return candidate
            found = shutil.which(selected)
            if found:
                self.multiwfn_path.set(found)
                self.save_config()
                return Path(found)
        raise FileNotFoundError("Multiwfn executable was not selected or could not be found.")

    def validate_generation_inputs(self) -> tuple[Path, Path, Path]:
        wf = Path(self.wavefunction_path.get().strip())

        if self.output_dir.get().strip():
            outdir = Path(self.output_dir.get().strip())
        else:
            outdir = wf.with_suffix("").parent / f"{wf.stem}_NCI"

        if not wf.exists():
            raise FileNotFoundError("No valid wavefunction file selected.")

        if wf.suffix.lower() in REJECTED_EXTS:
            raise ValueError("ORCA .out/.log files are not valid NCI inputs. Use .wfn or .wfx.")

        if wf.suffix.lower() not in SUPPORTED_WAVEFUNCTION_EXTS:
            raise ValueError(f"Unsupported wavefunction file type: {wf.suffix}")

        mwfn = self.ensure_multiwfn_available()

        return wf, mwfn, outdir

    def start_generate_nci(self, auto_open: bool = False) -> None:
        try:
            wf, mwfn, outdir = self.validate_generation_inputs()
        except Exception as exc:
            messagebox.showerror("Input error", str(exc))
            self.log(f"ERROR: {exc}")
            return

        if not self.generation_lock.acquire(blocking=False):
            self.log("NCI generation is already running. Waiting for the current Multiwfn job to finish.")
            return

        self.save_config()
        self.rdg_cube = None
        self.signrho_cube = None
        self.rdg_cube_path = None
        self.signrho_cube_path = None
        if self.generate_button is not None:
            self.generate_button.configure(state="disabled")
        thread = threading.Thread(
            target=self.generate_nci_worker,
            args=(wf, mwfn, outdir, auto_open),
            daemon=True,
        )
        thread.start()

    def _prepare_multiwfn_batch_input(self, template_text: str) -> tuple[str, list[str]]:
        commands: list[str] = []
        for raw_line in template_text.splitlines():
            line = raw_line.strip()
            if not line:
                continue
            if line.startswith("#"):
                continue
            commands.append(line)

        if not commands:
            raise RuntimeError(
                "The Multiwfn command template does not contain any executable commands after removing comments."
            )

        # Multiwfn may pause at startup with 'Press ENTER button to continue'
        # before showing the main menu. A leading blank line safely satisfies
        # that prompt without changing the subsequent command sequence.
        batch_text = "\n" + "\n".join(commands) + "\n"
        return batch_text, commands

    def generate_nci_worker(self, wf: Path, mwfn: Path, outdir: Path, auto_open: bool = False) -> None:
        try:
            outdir.mkdir(parents=True, exist_ok=True)
            self.output_dir.set(str(outdir))

            self.log(f"Output folder: {outdir}")

            existing_rdg, existing_signrho = self.detect_nci_cubes(outdir)
            if not (existing_rdg and existing_signrho) and wf.parent != outdir:
                existing_rdg, existing_signrho = self.detect_nci_cubes(wf.parent)
                if existing_rdg and existing_signrho:
                    self.output_dir.set(str(wf.parent))
            if existing_rdg and existing_signrho:
                self.log("Existing NCI cube files were found in the output folder.")
                self.log(f"Reusing RDG cube: {existing_rdg}")
                self.log(f"Reusing sign(lambda2)rho cube: {existing_signrho}")
                self.root.after(0, self.load_cubes_and_plot)
                return

            self.log("No existing NCI cube pair was found. Running Multiwfn to generate them.")

            template_text = self.command_template.get()
            if not template_text.strip():
                raise RuntimeError("Multiwfn command template is empty.")

            batch_text, commands = self._prepare_multiwfn_batch_input(template_text)

            if commands == ["q"]:
                raise RuntimeError(
                    "The saved Multiwfn command template contains only 'q', so Multiwfn exits immediately. "
                    "Open 'Edit Multiwfn command template' and click 'Reset default', or restart the script to reload the upgraded default template."
                )

            self.log("Using Multiwfn NCI route from the command template.")
            self.log("Default 2026.x route is: 20 -> 1 -> 3 -> 3 -> 0 -> q.")
            self.log("Expected files: func1.cub = sign(lambda2)rho; func2.cub = RDG.")
            self.log("Comment lines are stripped before execution.")
            self.log("A leading ENTER is added automatically for the initial Multiwfn startup prompt.")

            script_path = outdir / "multiwfn_nci_input.txt"
            script_path.write_text(batch_text, encoding="utf-8")

            self.log("Running Multiwfn in batch mode...")
            self.log(f"Command script: {script_path}")
            self.log("Effective command sequence: " + " -> ".join(commands))

            cmd = [str(mwfn), str(wf)]

            with script_path.open("r", encoding="utf-8") as stdin:
                proc = subprocess.run(
                    cmd,
                    stdin=stdin,
                    stdout=subprocess.PIPE,
                    stderr=subprocess.PIPE,
                    cwd=str(outdir),
                    text=True,
                    errors="replace",
                    shell=False,
                )

            stdout_path = outdir / "multiwfn_stdout.txt"
            stderr_path = outdir / "multiwfn_stderr.txt"
            stdout_path.write_text(proc.stdout or "", encoding="utf-8", errors="replace")
            stderr_path.write_text(proc.stderr or "", encoding="utf-8", errors="replace")

            self.log("Multiwfn finished.")
            self.log(f"Multiwfn stdout saved to: {stdout_path}")
            self.log(f"Multiwfn stderr saved to: {stderr_path}")

            rdg, signrho = self.detect_nci_cubes(outdir)

            if proc.returncode != 0:
                if rdg and signrho:
                    self.log(
                        f"WARNING: Multiwfn exited with return code {proc.returncode}, "
                        "but the required NCI cube files were generated successfully."
                    )
                    self.log("Continuing with the generated cubes.")
                else:
                    self.log(f"ERROR: Multiwfn failed with return code {proc.returncode}.")
                    self.log(f"See: {stdout_path}")
                    self.log(f"See: {stderr_path}")
                    raise RuntimeError("Multiwfn failed. Check the log files in the output folder.")

            if not rdg or not signrho:
                self.log("ERROR: Could not automatically identify RDG and sign(lambda2)rho cube files.")
                raise RuntimeError(
                    "Expected NCI cube files were not detected automatically. "
                    "The Multiwfn command template likely needs adjustment for your Multiwfn version."
                )

            self.log(f"Detected RDG cube: {rdg}")
            self.log(f"Detected sign(lambda2)rho cube: {signrho}")

            self.root.after(0, self.load_cubes_and_plot)

        except Exception as exc:
            self.log(f"ERROR: {exc}")
            self.root.after(0, lambda e=exc: messagebox.showerror("NCI generation failed", str(e)))
        finally:
            self.generation_lock.release()
            if self.generate_button is not None:
                self.root.after(0, lambda: self.generate_button.configure(state="normal"))

    def detect_nci_cubes(self, outdir: Path) -> tuple[Optional[Path], Optional[Path]]:
        cube_files = list(outdir.glob("*.cube")) + list(outdir.glob("*.cub"))

        # Multiwfn NCI post-processing convention:
        #   func1.cub = sign(lambda2)rho
        #   func2.cub = RDG
        func1 = outdir / "func1.cub"
        func2 = outdir / "func2.cub"

        if func1.exists() and func2.exists():
            return func2, func1

        func1_cube = outdir / "func1.cube"
        func2_cube = outdir / "func2.cube"

        if func1_cube.exists() and func2_cube.exists():
            return func2_cube, func1_cube

        rdg_candidates = []
        signrho_candidates = []

        for f in cube_files:
            name = f.name.lower()

            if "rdg" in name or "reduced" in name or "grad" in name:
                rdg_candidates.append(f)

            if (
                "sign" in name
                or "lambda" in name
                or "lambda2" in name
                or "rho" in name
                or "sl2r" in name
            ):
                signrho_candidates.append(f)

        rdg = rdg_candidates[0] if rdg_candidates else None
        signrho = signrho_candidates[0] if signrho_candidates else None

        if rdg and signrho and rdg == signrho:
            signrho = None

        return rdg, signrho

    def load_cubes_and_plot(self) -> None:
        try:
            rdg_path, signrho_path = self.detect_nci_cubes(Path(self.output_dir.get().strip()))
            if rdg_path is None or signrho_path is None:
                raise FileNotFoundError(
                    "Could not find generated RDG and sign(lambda2)rho cube files in the output folder."
                )

            if not rdg_path.exists():
                raise FileNotFoundError(f"RDG cube file not found: {rdg_path}")

            if not signrho_path.exists():
                raise FileNotFoundError(f"sign(lambda2)rho cube file not found: {signrho_path}")

            self.log("Loading cube files...")
            self.rdg_cube = CubeParser.parse(rdg_path)
            self.signrho_cube = CubeParser.parse(signrho_path)
            self.rdg_cube_path = rdg_path
            self.signrho_cube_path = signrho_path

            if self.rdg_cube.shape != self.signrho_cube.shape:
                raise CubeParseError(
                    f"Cube grid shape mismatch: RDG {self.rdg_cube.shape}, "
                    f"sign(lambda2)rho {self.signrho_cube.shape}"
                )

            self.log(f"Loaded RDG cube: {rdg_path}")
            self.log(f"Loaded sign(lambda2)rho cube: {signrho_path}")
            self.update_plot()

        except Exception as exc:
            self.log(f"ERROR: {exc}")
            messagebox.showerror("Cube loading failed", str(exc))

    def make_uniform_grid(self):
        try:
            import pyvista as pv
        except Exception as exc:
            raise RuntimeError("PyVista/VTK is not installed. Install with: pip install pyvista") from exc

        if self.rdg_cube is None or self.signrho_cube is None:
            raise RuntimeError("Cube data not loaded.")

        rdg = self.rdg_cube
        signrho = self.signrho_cube

        spacing = np.array(
            [
                np.linalg.norm(rdg.axes[0]),
                np.linalg.norm(rdg.axes[1]),
                np.linalg.norm(rdg.axes[2]),
            ],
            dtype=float,
        )

        diagonal_axes = np.diag(np.diag(rdg.axes))
        if not np.allclose(rdg.axes, diagonal_axes, atol=1e-6):
            self.log("WARNING: Non-orthogonal cube grid detected. PyVista ImageData assumes orthogonal axes.")

        try:
            grid = pv.ImageData()
        except AttributeError:
            grid = pv.UniformGrid()

        grid.dimensions = np.array(rdg.shape) + 1
        grid.origin = tuple(float(x) for x in rdg.origin)
        grid.spacing = tuple(float(x) for x in spacing)

        rdg_values = rdg.values.ravel(order="F")
        signrho_values = signrho.values.ravel(order="F")

        grid.cell_data["RDG"] = rdg_values
        grid.cell_data[NCI_SCALAR_NAME] = signrho_values

        return grid

    def is_plotter_alive(self) -> bool:
        if self.plotter is None:
            return False

        try:
            if getattr(self.plotter, "render_window", None) is None:
                return False

            if getattr(self.plotter, "iren", None) is None:
                return False

            if hasattr(self.plotter, "closed") and self.plotter.closed:
                return False

            return True

        except Exception:
            return False

    def close_dead_plotter_reference(self) -> None:
        if self.plotter is None:
            return

        try:
            self.plotter.close()
        except Exception:
            pass

        self.plotter = None

    def update_plot(self) -> None:
        try:
            import pyvista as pv
        except Exception as exc:
            messagebox.showerror(
                "PyVista missing",
                "PyVista/VTK is not installed.\n\nInstall with:\npy -3.12 -m pip install pyvista",
            )
            self.log(f"ERROR: PyVista/VTK not installed: {exc}")
            return

        try:
            if self.rdg_cube is None or self.signrho_cube is None:
                if self.generation_lock.locked():
                    self.log("NCI generation is still running. The plot will be available after Multiwfn finishes.")
                    return

                output_text = self.output_dir.get().strip()
                if not output_text:
                    self.log("No NCI cube files loaded yet. Select a WFN/WFX file and click 'Generate NCI data'.")
                    return

                rdg_path, signrho_path = self.detect_nci_cubes(Path(output_text))

                if rdg_path is not None and signrho_path is not None:
                    self.rdg_cube = CubeParser.parse(Path(rdg_path))
                    self.signrho_cube = CubeParser.parse(Path(signrho_path))
                else:
                    self.log(
                        "No generated NCI cube pair found yet. "
                        "Click 'Generate NCI data' or select a folder that already contains RDG and sign(lambda2)rho cubes."
                    )
                    return

            isovalue = float(self.rdg_isovalue.get())
            opacity = float(self.opacity.get())
            clim_min = float(self.color_min.get())
            clim_max = float(self.color_max.get())

            if clim_min >= clim_max:
                raise ValueError("Color scale minimum must be smaller than maximum.")

            grid = self.make_uniform_grid()
            # Convert cell data to point data for contour operation
            grid = grid.cell_data_to_point_data()
            surface = grid.contour(isosurfaces=[isovalue], scalars="RDG")
            sampled = surface.sample(grid)

            if sampled.n_points == 0:
                raise RuntimeError(
                    f"No RDG isosurface found at isovalue {isovalue}. "
                    "Try a different RDG isovalue."
                )

            self.close_dead_plotter_reference()
            bounds = sampled.bounds
            extent = float(np.linalg.norm([bounds[1] - bounds[0], bounds[3] - bounds[2], bounds[5] - bounds[4]]))
            self.plotter = pv.Plotter(window_size=(1200, self.window_height))
            bg_color = self.background.get()
            text_color = contrast_text_color(bg_color)
            self.plotter.set_background(bg_color)

            molecule_renderer = None
            if opacity < 0.999:
                try:
                    self.plotter.ren_win.SetNumberOfLayers(2)
                    molecule_renderer = pv._vtk.vtkRenderer()
                    molecule_renderer.SetLayer(1)
                    molecule_renderer.InteractiveOff()
                    molecule_renderer.SetViewport(0.0, 0.0, 1.0, 1.0)
                    molecule_renderer.SetActiveCamera(self.plotter.renderer.GetActiveCamera())
                    configure_molecule_renderer_lights(pv, molecule_renderer, extent)
                    self.plotter.ren_win.AddRenderer(molecule_renderer)
                except Exception:
                    molecule_renderer = None

            scalar_bar_args = {
                "title": NCI_SCALAR_BAR_TITLE,
                "vertical": True,
                "position_x": 0.86,
                "position_y": 0.15,
                "height": 0.7,
                "width": 0.08,
                "color": text_color,
                "title_font_size": 16,
                "label_font_size": 12,
            }

            self.plotter.add_mesh(
                sampled,
                scalars=NCI_SCALAR_NAME,
                cmap=self.colormap.get(),
                clim=[clim_min, clim_max],
                opacity=opacity,
                smooth_shading=False,
                scalar_bar_args=scalar_bar_args if self.show_scalar_bar.get() else None,
                show_scalar_bar=self.show_scalar_bar.get(),
            )
            if self.show_scalar_bar.get():
                set_scalar_bar_text_color(self.plotter, text_color, NCI_SCALAR_BAR_TITLE)

            if self.show_molecule.get():
                self.add_molecule_to_plotter(self.plotter, molecule_renderer)

            self.plotter.reset_camera()
            if molecule_renderer is not None:
                try:
                    molecule_renderer.SetActiveCamera(self.plotter.renderer.GetActiveCamera())
                except Exception:
                    pass
                try:
                    self.plotter.add_on_render_callback(
                        lambda plotter: molecule_renderer.SetActiveCamera(plotter.renderer.GetActiveCamera()),
                        render_event=True,
                    )
                except Exception:
                    pass
            bring_pyvista_window_to_front(self.plotter)
            self.plotter.show(interactive_update=True, auto_close=False)
            bring_pyvista_window_to_front(self.plotter, delay_s=0.05)

            self.log("Plot updated.")

        except Exception as exc:
            self.log(f"ERROR: {exc}")
            messagebox.showerror("Plot update failed", str(exc))

    def add_molecule_to_plotter(self, plotter, molecule_renderer=None) -> None:
        try:
            import pyvista as pv
        except Exception:
            return

        if self.rdg_cube is None:
            return

        atoms = self.rdg_cube.atom_coords
        numbers = self.rdg_cube.atom_numbers

        if atoms is None or len(atoms) == 0:
            self.log("No atom coordinates found in cube file.")
            return

        if self.show_bonds.get():
            bonds = self.guess_bonds(numbers, atoms)

            for i, j in bonds:
                p1 = np.asarray(atoms[i], dtype=float)
                p2 = np.asarray(atoms[j], dtype=float)
                midpoint = (p1 + p2) / 2.0

                for a, b, color in (
                    (p1, midpoint, self.atom_color(numbers[i])),
                    (midpoint, p2, self.atom_color(numbers[j])),
                ):
                    direction = b - a
                    length = float(np.linalg.norm(direction))

                    if length <= 0:
                        continue

                    cylinder = pv.Cylinder(
                        center=tuple(float(x) for x in (a + b) / 2.0),
                        direction=tuple(float(x) for x in direction / length),
                        radius=0.075,
                        height=length,
                        resolution=48,
                        capping=True,
                    )
                    self.add_molecule_mesh(plotter, cylinder, color, molecule_renderer)

        for number, coord in zip(numbers, atoms):
            radius = self.atom_display_radius(number)
            sphere = pv.Sphere(
                radius=radius,
                center=tuple(float(x) for x in coord),
                theta_resolution=64,
                phi_resolution=64,
            )
            self.add_molecule_mesh(plotter, sphere, self.atom_color(number), molecule_renderer)

    def add_molecule_mesh(self, plotter, mesh, color: str, molecule_renderer=None) -> None:
        if molecule_renderer is None:
            add_mesh_safe(plotter, mesh, color=color, **molecule_material_parameters())
            return

        try:
            import pyvista as pv
            mapper = pv._vtk.vtkPolyDataMapper()
            mapper.SetInputData(mesh)
            actor = pv._vtk.vtkActor()
        except Exception:
            add_mesh_safe(plotter, mesh, color=color, **molecule_material_parameters())
            return

        actor.SetMapper(mapper)
        prop = actor.GetProperty()
        rgb = hex_to_rgb01(color)
        prop.SetColor(float(rgb[0]), float(rgb[1]), float(rgb[2]))
        material = molecule_material_parameters()
        try:
            prop.LightingOn()
            prop.SetInterpolationToPhong()
            prop.SetAmbient(float(material["ambient"]))
            prop.SetDiffuse(float(material["diffuse"]))
            prop.SetSpecular(float(material["specular"]))
            prop.SetSpecularPower(float(material["specular_power"]))
        except Exception:
            pass
        molecule_renderer.AddActor(actor)

    def atom_display_radius(self, atomic_number: int) -> float:
        radius = self.covalent_radius(atomic_number) * 0.42
        return float(np.clip(radius, 0.16, 0.55))

    def atom_color(self, atomic_number: int) -> str:
        return ATOM_COLORS.get(atomic_number, "#FF69B4")

    def covalent_radius(self, atomic_number: int) -> float:
        return COVALENT_RADII.get(atomic_number, 0.77)

    def guess_bonds(self, numbers: list[int], coords: np.ndarray) -> list[tuple[int, int]]:
        bonds = []
        n = len(numbers)

        for i in range(n):
            for j in range(i + 1, n):
                dist = float(np.linalg.norm(coords[i] - coords[j]))
                cutoff = 1.20 * (
                    self.covalent_radius(numbers[i]) + self.covalent_radius(numbers[j])
                )

                if 0.35 < dist < cutoff:
                    bonds.append((i, j))

        return bonds

    def reset_view(self) -> None:
        if self.rdg_cube is None or self.signrho_cube is None:
            self.log("No plot data loaded yet. Generate NCI data first.")
            return

        # Restore default visualization settings
        self.rdg_isovalue.set(0.50)
        self.opacity.set(0.75)
        self.color_min.set("-0.05")
        self.color_max.set("0.05")
        self.colormap.set("rainbow")
        self.show_molecule.set(True)
        self.show_bonds.set(True)
        self.show_scalar_bar.set(True)
        self.background.set("white")

        self.log("Reset view: restored default visualization settings and redrawing clean plot window.")
        self.close_dead_plotter_reference()
        self.update_plot()

    def save_image(self) -> None:
        if not self.is_plotter_alive():
            messagebox.showerror("No plot", "No active PyVista plot to save. Use Update plot or Reset view to reopen it.")
            return

        path = filedialog.asksaveasfilename(
            title="Save image",
            defaultextension=".png",
            filetypes=[("PNG image", "*.png"), ("All files", "*.*")],
        )

        if not path:
            return

        try:
            image_size = self.selected_image_size()
            if image_size:
                save_pyvista_screenshot(self.plotter, path, self.background.get(), window_size=image_size, scale=1)
            else:
                save_pyvista_screenshot(self.plotter, path, self.background.get())
            self.save_config()
            self.log(f"Image saved: {path}")
        except Exception as exc:
            self.log(f"ERROR: Could not save image: {exc}")
            messagebox.showerror("Save failed", str(exc))

    def open_nci_qtaim_overlay(self) -> None:
        overlay_script = TOOLS_ROOT / "NCI_QTAIM_overlay" / "nci_qtaim_overlay.py"
        command = [sys.executable, str(overlay_script)]

        wavefunction = self.wavefunction_path.get().strip()
        qtaim_path_file = None
        if wavefunction and Path(wavefunction).is_file():
            command.append(wavefunction)
            try:
                overlay_module_path = overlay_script
                import importlib.util
                spec = importlib.util.spec_from_file_location("crystengkit_overlay_probe", str(overlay_module_path))
                if spec is not None and spec.loader is not None:
                    overlay_probe = importlib.util.module_from_spec(spec)
                    spec.loader.exec_module(overlay_probe)
                    qtaim_path_file = overlay_probe.find_qtaim_path_file(Path(wavefunction).parent, Path(wavefunction).stem)
            except Exception:
                qtaim_path_file = None
        if qtaim_path_file is not None:
            command.extend(["--paths", str(qtaim_path_file)])
        if self.rdg_cube_path and self.rdg_cube_path.is_file():
            command.extend(["--rdg", str(self.rdg_cube_path)])
        if self.signrho_cube_path and self.signrho_cube_path.is_file():
            command.extend(["--signrho", str(self.signrho_cube_path)])
        image_size = self.selected_image_size()
        if image_size is None and self.is_plotter_alive():
            try:
                image_size = tuple(int(v) for v in self.plotter.window_size)
            except Exception:
                image_size = None
        if image_size:
            command.extend(["--image-width", str(image_size[0]), "--image-height", str(image_size[1])])
        command.extend(
            [
                "--rdg-isovalue", str(float(self.rdg_isovalue.get())),
                "--opacity", str(float(self.opacity.get())),
                "--color-min", str(self.color_min.get()),
                "--color-max", str(self.color_max.get()),
                "--colormap", str(self.colormap.get()),
                "--background", str(self.background.get()),
                "--show-molecule", "1" if bool(self.show_molecule.get()) else "0",
                "--show-nci", "1",
            ]
        )

        try:
            subprocess.Popen(command, cwd=str(overlay_script.parent))
            self.log("Opened NCI + QTAIM overlay.")
        except Exception as exc:
            self.log(f"ERROR: Could not open NCI + QTAIM overlay: {exc}")
            messagebox.showerror("Overlay failed", str(exc))

    def edit_template_dialog(self) -> None:
        win = tk.Toplevel(self.root)
        win.title("Edit Multiwfn command template")
        win.geometry(f"800x{screen_fraction_height(win)}")
        configure_builder_ui_style(win)

        frame = ttk.Frame(win, style="Panel.TFrame", padding=10)
        frame.pack(fill="both", expand=True)

        info = (
            "Insert the exact Multiwfn batch command sequence for generating NCI/RDG cube files.\n"
            "This is version-dependent, so the default template is intentionally not assumed to be correct.\n"
            "The command is run as: Multiwfn input.wfn < this_template.txt\n"
        )
        ttk.Label(frame, text=info, justify="left").pack(anchor="w", pady=(0, 8))

        text = tk.Text(frame, wrap="none", font=("Consolas", 10), relief="solid", bd=1)
        text.pack(fill="both", expand=True)
        text.insert("1.0", self.command_template.get())

        button_frame = ttk.Frame(frame)
        button_frame.pack(fill="x", pady=(8, 0))

        def save_and_close() -> None:
            self.command_template.set(text.get("1.0", "end-1c"))
            self.save_config()
            self.log("Multiwfn command template updated.")
            win.destroy()

        def reset_template() -> None:
            text.delete("1.0", "end")
            text.insert("1.0", DEFAULT_MULTIWFN_TEMPLATE)

        ttk.Button(button_frame, text="Save", command=save_and_close).pack(
            side="left", padx=(0, 6)
        )
        ttk.Button(button_frame, text="Reset default", command=reset_template).pack(
            side="left", padx=6
        )
        ttk.Button(button_frame, text="Cancel", command=win.destroy).pack(side="right")

    def on_close(self) -> None:
        self.save_config()
        try:
            if self.plotter is not None:
                self.plotter.close()
        except Exception:
            pass
        self.root.destroy()


def main() -> None:
    initial_wavefunction_path = sys.argv[1] if len(sys.argv) > 1 else None
    root = tk.Tk()
    app = NCIPlotterApp(root, initial_wavefunction_path=initial_wavefunction_path)
    root.protocol("WM_DELETE_WINDOW", app.on_close)
    root.mainloop()


if __name__ == "__main__":
    main()
